(globalThis["webpackChunk_canva_web"] = globalThis["webpackChunk_canva_web"] || []).push([[38588],{

/***/ 666625:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);__web_req__(499464);__web_req__(737068);__web_req__(998520);__web_req__(270937);globalThis._456c437108d2d2713799e19380be528d = globalThis._456c437108d2d2713799e19380be528d || {};(function(__c) {__c.lHf=function(a,b="medium"){const c=(0,__c.Ob)(iHf,jHf,kHf),d=__c.lma(b);return(0,__c.db)(()=>__c.mma(a,d,c),[a,c,void 0,d])};__c.vQ=function({$y:a,children:b}){const c=(0,__c.db)(()=>({$y:a}),[a]);return(0,__c.E)(__c.tqa.Provider,{value:c,children:b})};__c.mHf=function(a){const b=(0,__c.luc)(()=>({render:a,JYb:(0,__c.guc)(c=>b.render=c)}));(0,__c.iuc)(()=>{b.JYb(a)},[a,b]);return(0,__c.quc)((0,__c.muc)(c=>b.render(c))).current};
__c.nHf=function(a){a=a.Br;return a.type==="STATIC_VIDEO_SOURCE"&&a.CB.some(b=>b.hasAudio)};
__c.tHf=function({uE:a,Fy:b,vE:c,M_:d,Sq:e}){return{epa:oHf(({card:f,oH:g,B5:k})=>{const l=__c.sc(),m=pHf(f.actions),q=f.title||f.menu?.title,t=m.like&&!l&&b?({className:F})=>wQ(b,{model:m.like,AAb:q,render:({onClick:G,Y:I,label:L})=>wQ(__c.OO,{icon:I,onClick:G,ariaLabel:L,className:qHf("Nu4jkQ",F)})},"like-button"):null,v=m.copy?({className:F})=>wQ(c,{action:m.copy,render:({onClick:G,Y:I,label:L})=>wQ(__c.MO,{visibility:__c.Gc()?"always":"on-hover",location:"bottom-start",children:wQ(__c.OO,{size:l?
"small":"medium",icon:I,onClick:G,ariaLabel:L,className:qHf("Nu4jkQ",F)})})}):null,y=rHf(()=>({isOpen:!1,toggle:xQ(()=>{y.isOpen=!y.isOpen;y.isOpen&&e&&e.pza()}),close:xQ(()=>y.isOpen=!1)})),z=f.Mv,A=f.r1a,C=f.lp;return wQ(sHf,{children:()=>yQ("div",{className:"phsQvg",children:[(A||z)&&wQ(d,{r1a:A,Mv:z,resourceType:C?.type}),v&&wQ(v,{}),k&&wQ(__c.MO,{visibility:"always",location:"bottom-start",children:wQ(k,{})}),yQ(__c.NO,{size:l?"small":"medium",visibility:__c.Gc()?"always":"on-hover",location:"top-end",
children:[t&&wQ(t,{}),m.yib.length>0&&wQ(__c.srf,{className:qHf("FaU_Wg",l&&"K4_fpQ"),ariaLabel:q?__c.H("jjfIpw",[q]):__c.J("sZenYQ"),x5:__c.lg,bua:wQ(a,{card:f,m6:y.close,oH:g}),isOpen:y.isOpen,Q4:y.toggle})]})]})})})}};__c.zQ=function({ma:[a]}){return(a&&__c.Xuc(a))??uHf};__c.Oh.prototype.NHc=__c.ca(24,function(){this.ULb=!1});
__c.Oh.prototype.Wwc=__c.ca(23,function(a,b,c){this.Pma.set(a,{ref:a,s6:b,IDb:"static",position:{left:0,top:0},visible:!1,Q5c:c});this.observer?.observe(a);return()=>{this.observer?.unobserve(a);this.Pma.delete(a)}});
var kHf=()=>1,jHf=()=>__c.tMa.get(),iHf=a=>(0,__c.KDa)(__c.tMa,a),vHf=({zgb:a})=>(0,__c.HI)("div",{className:"KYnMHQ",children:[__c.GI(__c.Lk,{icon:(0,__c.GI)(__c.vOc,{size:"tiny"}),tone:"contrast"}),a!=null&&__c.GI(__c.Lk,{icon:(0,__c.GI)(__c.zOc,{size:"tiny"}),tone:"contrast"})]}),wHf=__webpack_require__(296713),xHf=wHf.Fragment,wQ=wHf.jsx,yQ=wHf.jsxs;var yHf=__webpack_require__,zHf=yHf(208463),qHf=yHf.n_x(zHf)();var AHf=__webpack_require__(270531),rHf=AHf.iz,sHf=AHf.nu,oHf=AHf.PA;var BHf=__webpack_require__(978109),CHf=BHf.Component,DHf=BHf.memo,EHf=BHf.useEffect,FHf=BHf.useState;var GHf=__webpack_require__(186901),HHf=GHf.EW,IHf=GHf.h5,JHf=GHf.mJ,KHf=GHf.sH,xQ=GHf.XI;var LHf=__webpack_require__(549056)._;var MHf=__webpack_require__(621369)._;var pHf=a=>a.reduce((b,c)=>{switch(c.type){case "LIKE":return b.like=c,b.yib.push(c),b;case "COPY_ELEMENT":return b.copy=c,b.yib.push(c),b;default:return b.yib.push(c),b}},{like:void 0,copy:void 0,yib:[]});var uHf={width:400,height:300};var NHf;
__c.OHf=DHf(a=>{const b=a.Jc,c=a.Db,d=a.overlay,e=a.iI,f=a.title,g=a.subtitle,k=a.onMouseEnter,l=a.onMouseLeave,m=a.onMouseDown,q=a.onMouseUp,t=a.onFocus,v=a.onBlur,y=a.Otd,z=a.ega;a=a.ref;const {isVisible:A,hDc:C}=__c.wuc(),[F,G]=FHf(!1);EHf(()=>{var I=window;I=NHf==null?NHf=!!I.navigator.vendor.match(/apple/i):NHf;return G(I)},[]);return yQ("div",{className:"_6Jw7Rg",ref:a,children:[wQ("div",{ref:C,className:"gogj2g",children:wQ(__c.DO,{iI:yQ(xHf,{children:[e,z&&wQ(__c.MO,{location:"top-start",visibility:"always",
children:wQ(__c.wwc,{label:__c.J("YhEcCA")})})]}),FA:"none",Ua:yQ("div",{className:"v34KHg",onMouseUp:q,onMouseDown:m,onMouseEnter:k,onMouseLeave:l,onFocus:t,onBlur:v,children:[wQ(__c.KO,{children:c&&wQ("div",{className:"WZJFzw",style:{transform:y&&F?"translateZ(0)":void 0},children:c})}),d&&A&&wQ("div",{className:"_69kWDg",children:d})]}),layout:"vertical",Bw:"thumbnail"})}),b||f||g?yQ(__c.yd,{display:"flex",alignItems:g?void 0:"center",width:"full",paddingTop:"1u",children:[b&&wQ("div",{className:"zvuW2Q",
children:b}),f||g?yQ("div",{className:"p1dBAA",children:[f&&f,g&&g]}):null]}):null]})});var PHf,QHf,RHf;
new (PHf=class extends LHf{constructor(){super(__c.AQ);QHf()}},(()=>{class a extends(RHf=CHf){static F(b){__c.vb(b,{ZD:KHf.ref,lz:KHf.ref,isFocused:KHf.ref,cIc:xQ.bound,RA:xQ.bound,dma:xQ.bound,yC:xQ,y0:HHf,SY:HHf,title:HHf,c8:HHf})}cIc(b){this.ZD=b}componentDidMount(){this.Xwc();__c.Gb(this,JHf(()=>({lz:this.lz,isFocused:this.isFocused}),b=>{b.lz||b.isFocused?this.eBc(this.lz?"hover":"focus"):this.uKc()}))}componentWillUnmount(){this.pNc?.()}componentDidUpdate(b){b.Uh===void 0&&this.props.Uh&&this.Xwc()}get y0(){const b=
this.props.Uh;return this.ZD&&b?b.y0(this.ZD):!1}get SY(){const b=this.props.Uh;return this.ZD&&b?b.SY(this.ZD):!1}get title(){return this.props.title}get c8(){return this.props.c8}render(){const b=this.props.children,c=this.props.Uh;return b({ZD:this.cIc,y0:this.y0,SY:this.SY,B5:c&&this.B5,pAb:c&&!__c.Gc()?{RA:this.RA,dma:this.dma,onFocus:this.onFocus,onBlur:this.onBlur}:{},GTb:{SD:this.SD,yC:this.yC,MP:this.MP}})}constructor(...b){super(...b);this.ZD=(__c.AQ.F(this),null);this.isFocused=this.lz=
!1;this.isLoaded=KHf.box(!1);this.Hwb=[];this.Xwc=()=>{if(__c.Gc()){var c=this.props.Uh;this.pNc?.();this.pNc=c?.Wwc(this.ZD,this.props.s6,this.props.c8)}};this.eBc=c=>{const d=this.props.Uh,e=this.props.oX,f=this.props.c8;d&&this.ZD&&(c&&e&&(c==="click"?this.Hwb.push(()=>this.ZD&&d.CMc(c,this.isLoaded,f,e)):d.CMc(c,this.isLoaded,f,e)),d.fWb(this.ZD,{E$c:!0,V3b:c==="click"}))};this.uKc=c=>{const d=this.props.Uh,e=this.props.oX,f=this.props.c8;d&&this.ZD&&(c&&e&&d.v7d(this.ZD,f,e),d.pza(this.ZD,c===
"click"))};this.rqb=()=>{this.onClick();this.y0?this.uKc("click"):this.eBc("click")};this.qqb=()=>{this.onClick();const c=this.props.Uh,d=this.props.oX,e=this.props.c8;c&&this.ZD&&(this.SY?(d&&c.zMc("mute",this.ZD,e,d),c.Lo()):(d&&c.zMc("unmute",this.ZD,e,d),c.m2b(this.ZD,{H$c:!0,V3b:!0})))};this.RA=()=>{this.lz=!0};this.dma=()=>{this.lz=!1};this.afc=__c.ib(c=>{IHf(()=>this.isFocused=c)},50);this.onFocus=()=>{this.afc(!0)};this.onBlur=()=>{this.afc(!1)};this.onClick=()=>{if(this.lz)this.onBlur()};
this.MP=()=>{for(;this.Hwb.length>0;)this.Hwb.shift()?.()};this.SD=(c,d)=>{c.name==="NotAllowedError"&&(this.SY?(this.props.Uh?.Lo(),d?.()):(this.props.Uh?.pza(),this.props.Uh?.NHc()))};this.yC=()=>{this.isLoaded.set(!0)};this.B5=oHf(({EIe:c="swap-on-hover"})=>{const d=this.c8?this.SY:void 0,e=wQ(__c.AOc,{isPlaying:!!this.y0,rqb:this.rqb,zgb:d,qqb:this.qqb,title:this.title});return c!=="always"&&__c.Hc()?wQ(__c.ivc,{RA:e,children:wQ(vHf,{zgb:d})}):e})}}({c:[__c.AQ,QHf]}=MHf(a,[],[__c.Lb],RHf))})(),
PHf);
}).call(globalThis, globalThis._456c437108d2d2713799e19380be528d);}

}])
//# sourceMappingURL=sourcemaps/12b3bd117d6c13c1.js.map