(globalThis["webpackChunk_canva_web"] = globalThis["webpackChunk_canva_web"] || []).push([[84985],{

/***/ 93415:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);globalThis._456c437108d2d2713799e19380be528d = globalThis._456c437108d2d2713799e19380be528d || {};(function(__c) {var EC;var H=__c.H;var AC;var Lpc,Mpc,Npc,Opc,Ppc,Upc,Vpc,Wpc,Ypc;Lpc=function(a,b){const c=b.x,d=b.y,e=b.easing,f=b.duration;b=b.rtl;const {x:g,y:k}=__c.cja(a,{rtl:b});__c.ve(a,{x:c!=null?g+c:void 0,y:d!=null?k+d:void 0,easing:e,duration:f,rtl:b})};Mpc=function(a,b={}){const c=b.x,d=b.y;a=__c.ue(a);const e=__c.cja(a);__c.ve(a,{x:c!=null?c*e.Tk:void 0,y:d!=null?d*e.mA:void 0,easing:b.easing,duration:b.duration,rtl:b.rtl})};
Npc=function(a,b={}){const c=b.x,d=b.y;a=__c.ue(a);const e=__c.cja(a);Lpc(a,{x:c!=null?c*e.Tk:void 0,y:d!=null?d*e.mA:void 0,easing:b.easing,duration:b.duration,rtl:b.rtl})};Opc=function(a,b){return(a=typeof a==="function"?a():a)&&AC("span",{className:b,children:a})};Ppc=function({role:a,active:b,selected:c,pressed:d}){switch(a){case "switch":return{q2pazA:!1,njAsng:c??b};case "button":case "combobox":return{q2pazA:d??b,njAsng:c};default:throw new __c.n(a);}};
__c.Tpc=function(a){const {onScroll:b,UV:c,tR:d=0}=a,e=__c.hb()==="RTL",f=(0,__c.Qpc)(null);a=__c.fb();const g=__c.je(),k=!a||g,l=BC(()=>({I7:()=>{if(f.current)return __c.eja(f.current,{rtl:e})},scrollTo:q=>{f.current&&__c.ve(f.current,{rtl:e,...q,easing:k?"instant":q.easing||"smooth"})},scrollBy:q=>{f.current&&Lpc(f.current,{rtl:e,...q,easing:k?"instant":q.easing||"smooth"})},tnb:q=>{f.current&&Mpc(f.current,{rtl:e,...q,easing:k?"instant":q.easing||"smooth"})},Jya:q=>{f.current&&Npc(f.current,{rtl:e,
...q,easing:k?"instant":q.easing||"smooth"})}}),[e,k]);a=BC(()=>{if(b||c){var q=()=>{const t=l.I7();t&&(b?.(t),c?.(t))};return d===0?q:__c.ib(q,d,{leading:!0})}},[b,c,d,l]);const m=BC(()=>{if(c){var q=()=>{const t=l.I7();t&&c?.(t)};return d===0?q:__c.ib(q,d,{leading:!0})}},[c,d,l]);(0,__c.Rpc)(()=>{if(f.current&&m){var q=new Spc["default"](()=>m());q.observe(f.current);var t=new MutationObserver(()=>m());t.observe(f.current,{childList:!0,subtree:!0});return()=>{q.disconnect();t.disconnect()}}},[m]);
return{ref:(0,__c.CC)(q=>{(f.current=q)&&m?.()},[m]),handle:l,onScroll:a}};Upc=function(a){switch(a){case "canvas":return"CUb7yA";case "tabdock":return"halDGQ";case "surface":return"rVH_Og";case "page":return"jbzAYg";default:throw new __c.n(a);}};Vpc=function(a){switch(a){case "vertical":return"fYglDA";case "horizontal":return"rgskyw";default:throw new __c.n(a);}};
Wpc=[{Qha:1E3,w7:a=>H("BQkOCQ",[a])},{Qha:1E4,w7:a=>H("7KQN4Q",[a])},{Qha:1E5,w7:a=>H("k99f+Q",[a])},{Qha:1E6,w7:a=>H("A/yo4g",[a])},{Qha:1E7,w7:a=>H("UY/ePA",[a])},{Qha:1E8,w7:a=>H("VD4ycQ",[a])},{Qha:1E9,w7:a=>H("B9m98A",[a])}];
__c.Xpc=class{aR(a){const b=__c.Zaa(this.Ntd||window.navigator.language);for(let g=0;g<Wpc.length;g++){var c=Wpc[g],d=c.Qha;var e=a;e=this.Sdb?.maximumSignificantDigits?Number(e.toPrecision(this.Sdb.maximumSignificantDigits))||e:e;if(d>e)if(f==null||f.w7("")==="")break;else return a=(a/f.Qha).toLocaleString(b,this.Sdb),f.w7(a);d=c;if(f==null)var f=d;else c=f.w7(""),e=d.w7(""),f=c===e?f:d}return a.toLocaleString(b,this.Sdb)}constructor(a,b){this.Ntd=a;this.Sdb=b}};Ypc=__webpack_require__(296713);
AC=__c.AC=Ypc.jsx;__c.DC=Ypc.jsxs;var Zpc,$pc;Zpc=__webpack_require__;$pc=Zpc(208463);EC=__c.EC=Zpc.n_x($pc)();var FC,aqc,BC;FC=__webpack_require__(978109);__c.CC=FC.useCallback;__c.Rpc=FC.useEffect;aqc=FC.useImperativeHandle;BC=FC.useMemo;__c.Qpc=FC.useRef;__c.bqc=FC.useState;__c.cqc=__webpack_require__(245307).Fm;__c.dqc=__webpack_require__(594314).A;var Spc=__webpack_require__(294462);__c.GC=({text:a,size:b="xsmall",shape:c,active:d,selected:e,pressed:f,disabled:g,maxWidth:k="25u",fma:l,onClick:m,start:q,end:t,id:v,role:y="button",Ui:z=y==="combobox",ariaLabel:A,zb:C,md:F,Uf:G,ariaHasPopup:I,mt:L,ariaInvalid:O,fd:P,aD:R,cu:U,gj:W,NW:Z,ref:Y})=>{const S=__c.Bd(),{ref:ia,vda:ja}=__c.Rd(a),ka=P||(ja?a:void 0),da=EC("KpncAQ",{Mk7oNw:!l,_336cvg:b==="tiny",Suy2NA:b==="xsmall",QNHArA:b==="small",ilYYXw:b==="medium",lDt8Cg:b==="large",MFWj2A:c==="rectangle",IUH4gg:g,yt9Bhw:k==="25u",_0E9Wig:S,
...Ppc({role:y,active:d,selected:e,pressed:f})}),la=Opc(q,"p0GsKw");c=Opc(t,"lm_klw");const ta=AC(__c.K,{ref:ia,tagName:"span",className:"_SDvMQ",tone:__c.Id,size:b==="tiny"?"small":"medium",lineClamp:1,children:a});return l!=null&&ka!=null?AC(__c.Qd,{label:ka,description:R,disabled:U,lineClamp:Z,placement:W,children:({V$:pa,...Ca})=>(0,__c.DC)("span",{id:v,className:da,"aria-label":A,"aria-labelledby":C,"aria-describedby":F??(a!==ka?pa:void 0),...Ca,children:[la,ta,AC(__c.Ud,{ref:Y,onClick:l,size:b===
"large"?"medium":b==="medium"?"small":"tiny",variant:"tertiary",className:"aDxY_Q",icon:__c.dk,qf:"small",ariaLabel:H("kZXcBA",[a]),disabled:g})]})}):l!=null?(0,__c.DC)("span",{id:v,className:da,"aria-label":A,"aria-labelledby":C,"aria-describedby":F,children:[la,ta,AC(__c.Ud,{ref:Y,onClick:l,size:b==="large"?"medium":b==="medium"?"small":"tiny",variant:"tertiary",className:"aDxY_Q",icon:__c.dk,qf:"small",ariaLabel:H("kZXcBA",[a]),disabled:g})]}):__c.DC(__c.Yd,{ref:Y,id:v,onClick:m,className:da,Jla:!0,
role:y==="button"?void 0:y,active:d,selected:e,pressed:f,disabled:g,Ui:z,ariaLabel:A,zb:C,md:F,Uf:G,mt:L,ariaHasPopup:I,ariaInvalid:O,fd:ka,aD:R,cu:U,gj:W,NW:Z,children:[la,ta,c]})};__c.eqc=parseInt("2000ms",10)+100||2E3;var fqc=a=>{const {children:b,direction:c,onScroll:d,UV:e,tR:f=0,className:g,ariaLabel:k,role:l="region",ref:m}=a,{ref:q,handle:t,onScroll:v}=__c.Tpc({onScroll:d,UV:e,tR:f}),y=(0,__c.Qpc)(null);aqc(m,()=>({...t,v2e:()=>{var z=y.current;const A=__c.eja(z);return A.Sv?{Sv:A.Sv,dO:c==="vertical"?A.sxb:A.dO,cO:c==="vertical"?A.pxb:A.cO,raw:{scroll:{height:z.scrollHeight,width:z.scrollWidth,left:z.scrollLeft,top:z.scrollTop},client:{height:z.clientHeight,width:z.clientWidth,left:z.clientLeft,top:z.clientTop}}}:
{Sv:!1}}}));return AC("div",{tabIndex:0,"aria-label":k,role:k?l:void 0,className:EC("_4Qhg6w",g,{_3d4diw:c==="vertical",XcSaRA:c==="horizontal"}),ref:__c.nd(y,q),onScroll:v,children:b})};var gqc=typeof window!=="undefined"?/AppleWebKit\//i.test(window.navigator.userAgent):void 0,hqc=a=>{const [b,c]=(0,__c.bqc)(!1),[d,e]=(0,__c.bqc)(!1),[f,g]=(0,__c.bqc)(null);var k=__c.hb()==="RTL";const l=a.children,m=a.direction,q=a.onScroll,t=a.UV,v=a.tR,y=a.ariaLabel,z=a.role;var A=a.type,C=a.background;a=a.ref;const F=gqc&&k&&m==="horizontal",G=__c.fb(),I=(0,__c.CC)(R=>{const U=R.Tk,W=R.scrollWidth;!R.Sv||U===f?.client&&W===f?.scroll||g({client:U,scroll:W})},[f]),L=(0,__c.CC)(R=>{const U=m===
"horizontal"?R.dO:R.sxb,W=m==="horizontal"?R.cO:R.pxb;R.Sv?(c(!U),e(!W)):(c(!1),e(!1));F&&I(R)},[m,F,I]);k=BC(()=>{const R=t&&v?__c.ib(t,v,{leading:!0}):t;return U=>{L(U);R?.(U)}},[t,v,L]);const O=BC(()=>q&&v?__c.ib(q,v,{leading:!0}):q,[q,v]),P=EC("C96BFQ",Vpc(m));C=Upc(C);a:switch(A){case "shadow":A="czGiVQ";break a;case "fade":A="nIk0BA";break a;default:throw new __c.n(A);}A=EC("zTtbcw",C,A,Vpc(m),{cjUW4Q:G});return(0,__c.DC)(fqc,{direction:m,onScroll:O,UV:k,ariaLabel:y,role:z,ref:a,className:EC("_4VC3AQ",
Vpc(m)),children:[AC("div",{className:EC(P,"PIXMCA"),style:{right:F&&f?`${f.scroll-f.client}px`:void 0},children:AC("div",{className:EC(A,"PIXMCA",{z4ON1g:b})})}),AC("div",{className:EC(P,"lc5heg"),style:{right:F&&f?`${f.scroll}px`:void 0},children:AC("div",{className:EC(A,"lc5heg",{z4ON1g:d})})}),AC("div",{className:"hPdeUA",children:l})]})};__c.HC=a=>{const {children:b,direction:c="vertical",onScroll:d,UV:e,tR:f,Z1:g,ariaLabel:k,role:l,ref:m}=a;return g?AC(hqc,{direction:c,onScroll:d,UV:e,tR:f,ariaLabel:k,role:l,ref:m,type:g.type,background:g.background?g.background:"surface",children:b}):AC(fqc,{direction:c,onScroll:d,UV:e,tR:f,ariaLabel:k,role:l,ref:m,children:b})};
}).call(globalThis, globalThis._456c437108d2d2713799e19380be528d);}

}])
//# sourceMappingURL=sourcemaps/1434a8be5cd283ac.js.map