(globalThis["webpackChunk_canva_web"] = globalThis["webpackChunk_canva_web"] || []).push([[79095],{

/***/ 16433:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);__web_req__(487867);globalThis._456c437108d2d2713799e19380be528d = globalThis._456c437108d2d2713799e19380be528d || {};(function(__c) {var Fj=__c.Fj;var vI;var DMc,EMc,GMc,KMc,AMc,LMc,MMc,CI;__c.BMc=function({children:a,width:b,height:c,tagName:d="div",ref:e,...f}){return(0,__c.E)(d,{className:(0,__c.Vc)("_99GB9Q",AMc[b],{XIyMlA:c==="full"}),ref:e,...__c.Xc(f),children:a})};__c.CMc=function(a){let {r:b,g:c,b:d}=__c.af(a);c/=255;d/=255;a=b/255;return.2126*(a<=.03928?a/12.92:((a+.055)/1.055)**2.4)+.7152*(c<=.03928?c/12.92:((c+.055)/1.055)**2.4)+.0722*(d<=.03928?d/12.92:((d+.055)/1.055)**2.4)};
__c.uI=function(a,b){a=__c.Yf(a);b=__c.Yf(b);var c=a.getTime()>=b.getTime()?1:-1;a=Math.abs(a.getTime()-b.getTime())/864E5;c*=Math.floor(a);return c===0?0:c};__c.wI=function(a,b,c){const d=(e,f)=>{b.error(e,{Ja:`Error in marketplace subpage ${a}: `,extra:new Map(Object.entries(f))})};return function(e){return f=>vI(__c.ce,{cz:d,ema:c,children:vI(e,{...f})})}};DMc=function(a){switch(a){case "none":return"0";case "compact":return"1u";case "comfortable":return"2u";default:throw new __c.n(a);}};
EMc=function(a,b,c){return b>a?{width:"100%",height:`calc((((100% + ${c*2}px) * ${a}) - ${c*2}px) / ${b})`}:{width:`calc((((100% + ${c*2}px) / ${a}) - ${c*2}px) * ${b})`,height:"100%"}};__c.yI=function({tone:a="secondary",Y:b,size:c,background:d="secondary",border:e="low",padding:f="none",borderRadius:g="elementSmall",aspectRatio:k,width:l,height:m}){return vI(__c.xI,{aspectRatio:k,width:l,height:m,border:e,borderRadius:g,children:vI(__c.FMc,{background:d,padding:f,children:vI(b,{tone:a,size:c||"medium"})})})};
GMc=function(a){return new Promise((b,c)=>{const d=new Image;d.src=a;d.onload=()=>{b()};d.onerror=()=>{c()}})};
__c.JMc=function(a){const {Br:b,jm:c,playState:d="play",bpc:e,tPc:f,k7b:g=__c.Jk,vPc:k,Fid:l,Ohb:m,hSb:q,eGa:t,apc:v,Kfb:y,eQ:z=__c.zI,Vwa:A,Cyd:C,width:F,height:G,aspectRatio:I,border:L,borderRadius:O="none",muted:P=!0,autoplay:R=!0,ref:U}=a,W=__c.fb();a=HMc(S=>{const ia=ja=>ja==="loaded"&&vI(g,{autoPlay:W&&R,controls:!1,className:AI(f,"FtwUWA",{Mfh7dg:c!=null}),draggable:!1,loop:!0,muted:P,playsInline:!0,ref:U,src:S,poster:navigator!=null&&navigator.userAgent.indexOf("canvaeditor")>=0&&navigator.userAgent.match(/iphone|ipad/gi)?
"data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=":void 0});return k==null?vI(IMc,{src:S,delay:l||0,Ohb:m,callback:q,children:ja=>ia(ja)}):ia(k)},[U,c,f,l,k,g,W,m,q,P,R]);const Z=HMc(S=>vI(__c.BI,{src:S,xc:e,fallback:v,placeholder:y,alt:t,className:AI("cDIK1A",C),eQ:z,Vwa:A,border:"none",borderRadius:"none"}),[e,v,y,t,C,z,A]),Y=d==="play"&&(e!=="loading"||e==null);return CI(__c.xI,{aspectRatio:I,width:F,height:G,jAd:"ACLUKA",border:L,borderRadius:O,children:[c!=null&&Z(c),Y&&a(b)]})};
KMc=function(a){return new Promise((b,c)=>{const d=()=>{f.removeEventListener("loadeddata",d);b(f)},e=()=>{f.removeEventListener("error",e);c()},f=document.createElement("video");f.src=a;f.addEventListener("error",e);f.addEventListener("loadeddata",d);f.load()})};__c.Tua.prototype.Uda=__c.ca(27,function(a,b,c){if(this.NZb[a])return this.NZb[a]?.(b,c),!0;this.C&&this.C.warning(`TailoringDialogConfiguration tried to show "${a}" with source "${b}" but was not installed.`);return!1});
AMc={baseUnit:"8px",container:"_99GB9Q",medium:"hMc6MQ",large:"rzX2Ng",fullHeight:"XIyMlA"};LMc=__webpack_require__(296713);MMc=LMc.Fragment;vI=__c.vI=LMc.jsx;CI=LMc.jsxs;var DI,NMc,HMc,PMc,QMc;DI=__webpack_require__(978109);NMc=DI.createContext;HMc=DI.useCallback;__c.OMc=DI.useContext;PMc=DI.useEffect;QMc=DI.useState;var RMc=__webpack_require__,SMc=RMc(208463),AI=RMc.n_x(SMc)();var TMc=__webpack_require__(245307).Fm;var UMc=__webpack_require__(75402)._;var VMc=__webpack_require__(270531),WMc=VMc.iz,XMc=VMc.PA;var YMc=__webpack_require__(186901).XI;__c.EI=({dj:a,ST:b,Soa:c="none",Button:d,display:e="compact",width:f,children:g,ref:k})=>CI("section",{ref:k,className:AI("_sBzQQ",{hHCGKA:e==="compact",YTq_LA:f==="contained"}),children:[(()=>{if(a!=null&&b!=null){var l=vI("div",{className:"T7H5hQ",children:vI(a,{})}),m=vI(__c.Ie,{size:DMc(c),direction:"vertical"}),q=vI("div",{className:"sLd6Fg",children:vI(b,{})});a:switch(c){case "none":var t="0";break a;case "compact":t="2u";break a;case "comfortable":t="4u";break a;default:throw new __c.n(c);
}return CI(MMc,{children:[l,m,q,vI(__c.Ie,{size:t,direction:"vertical"})]})}if(a!=null)return CI(MMc,{children:[vI("div",{className:"T7H5hQ",children:vI(a,{})}),vI(__c.Ie,{size:DMc(c),direction:"vertical"})]});if(b!=null)return CI(MMc,{children:[vI("div",{className:"sLd6Fg",children:vI(b,{})}),vI(__c.Ie,{size:DMc(c),direction:"vertical"})]})})(),vI("div",{className:"wQhSMw",children:g}),d&&vI("div",{className:"MXTkEQ",children:vI(d,{})})]});var bNc,aNc,$Mc;__c.ZMc=NMc(void 0);__c.FMc=({children:a,className:b,background:c="secondary",border:d="none",borderRadius:e="elementSmall",fit:f="cover",padding:g="2u",height:k,width:l,aspectRatio:m})=>{m=$Mc({width:l,height:k,aspectRatio:m});return vI(aNc,{height:k,width:l,aspectRatio:m,children:vI("div",{className:AI("XkVKzg",b,bNc({background:c,border:d,borderRadius:e,padding:g})),children:vI(__c.ZMc.Provider,{value:{aspectRatio:m,padding:g,fit:f},children:a})})})};
bNc=({background:a,border:b,borderRadius:c,padding:d})=>AI({dUWjTg:a==="secondary",wUapkg:a==="contrastOnLight",CdiZ5g:a==="contrastOnDark",HRBU9g:a==="secondaryHover",duleYA:a==="contrastOnLightHover",_05M0zQ:a==="contrastOnDarkHover"},{PUHi3w:b!=="none",y_YfRw:b==="low",iedMZA:c==="elementSmall",sMv3zw:c==="element",Ol3xtA:c==="elementRelaxed",S0rWsg:c==="elementSoftest"},{_8z_brA:d==="1u",_4VVG1Q:d==="2u"});
aNc=({aspectRatio:a,width:b,height:c,children:d})=>{const e=Fj(b),f=Fj(c);return a!=null?vI(__c.ll,{ratio:a,width:b,height:c,children:d}):b!=null||c!=null?vI("div",{style:{width:e??"100%",height:f??"100%",flexShrink:0},children:d}):d};$Mc=({aspectRatio:a,width:b,height:c})=>{b=Fj(b);c=Fj(c);return a??(b!=null&&c!=null?b/c:void 0)};__c.xI=({width:a,height:b,aspectRatio:c,border:d="low",borderRadius:e="elementSmall",children:f,jAd:g})=>{var k=(0,__c.OMc)(__c.ZMc);c=$Mc({width:a,height:b,aspectRatio:c});const {aspectRatio:l,padding:m,fit:q}=k||{};k=c!=null&&l!=null;if(!k&&d==="none"&&e==="none"&&g==null)return vI(aNc,{height:b,width:a,aspectRatio:c,children:f});var t=m==="none"?0:Fj(m);t=k?q==null||q==="cover"?EMc(l,c,t):c>100/15?EMc(l,100/15,t):c<l*.75?{width:`calc((100% + ${t*2}px) * 0.75)`,height:`calc((100% + ${t*2}px) * 0.75 * ${l} / ${c})`,
transform:"translateY(50%)",marginTop:`calc(((100% + ${t*2}px) / ${l}  * -1) + ${t*2}px)`}:EMc(l,c,t):void 0;return vI(aNc,{height:b,width:a,aspectRatio:k?void 0:c,children:vI("div",{className:AI("gVI_3Q",g,{iedMZA:e==="elementSmall",sMv3zw:e==="element",Ol3xtA:e==="elementRelaxed",S0rWsg:e==="elementSoftest",PUHi3w:d!=="none",y_YfRw:d==="low"}),style:t,children:f})})};var dNc,cNc;__c.eNc=({xc:a,src:b,BYa:c=GMc,Vwa:d,eQ:e=__c.zI,...f})=>a==="none"?e({src:b,...f}):a==null&&b!=null?vI(cNc,{src:b,BYa:c,callback:d,children:g=>vI(dNc,{xc:g,src:b,eQ:e,...f})}):vI(dNc,{xc:a,src:b,eQ:e,...f});dNc=({src:a,xc:b,placeholder:c=vI(__c.fNc,{src:a}),fallback:d=vI(__c.yI,{Y:__c.Zj,border:"none"}),eQ:e=__c.zI,...f})=>vI(__c.Tj,{loading:b==="loading",expand:!0,placeholder:c,content:b==="error"?d:e({src:a,...f})});
__c.zI=({id:a,className:b,alt:c,crossOrigin:d,src:e,bTa:f,style:g,objectFit:k})=>vI("img",{id:a,className:AI(b,"ccn7hg",{BUSKzw:k==="contain",_4WF0QQ:k==="cover"}),crossOrigin:d,src:e,alt:c,draggable:!1,elementtiming:f,style:g});__c.fNc=({src:a,index:b,shape:c="sharpRectangle",kg:d})=>{b=vI(__c.md,{shape:c,index:b,kg:d});return a==null?b:CI(MMc,{children:[b,vI("noscript",{children:vI("img",{src:a,className:"_1zLfwg",draggable:!1,alt:""})})]})};
cNc=({src:a,callback:b,children:c,BYa:d})=>{const [e,f]=QMc("loading");PMc(()=>{(async()=>{const g=UMc()();try{b&&b("loading"),g.r(await g.s(d(a).then(TMc.wrap(()=>{f("loaded");b&&b("loaded")})).catch(TMc.wrap(()=>{f("error");b&&b("error")}))))}finally{g.s()}})()},[a,b,d]);return c(e)};__c.BI=({aspectRatio:a,border:b,borderRadius:c,width:d,height:e,...f})=>vI(__c.xI,{aspectRatio:a,borderRadius:c,border:b,width:d,height:e,children:vI(__c.eNc,{objectFit:"cover",id:f.id,crossOrigin:f.crossOrigin,bTa:f.bTa,src:f.src,alt:f.alt||"",className:f.className,style:f.style,BYa:f.BYa,xc:f.xc,Vwa:f.Vwa,placeholder:f.placeholder,fallback:f.fallback,eQ:f.eQ})});var IMc=XMc(function({src:a,delay:b,callback:c,Ohb:d=KMc,children:e}){const f=WMc(()=>({xc:"loading",zYb:YMc(g=>{f.xc=g})}));PMc(()=>{(async()=>{const g=UMc()();try{try{g.r(await g.s(__c.Ic(b))),f.zYb("loading"),c&&c("loading"),g.r(await g.s(d(a))),f.zYb("loaded")}catch(k){g.r(),f.zYb("error")}finally{c&&c(f.xc)}}finally{g.s()}})()},[a,f,c,d,b]);return e(f.xc)});
}).call(globalThis, globalThis._456c437108d2d2713799e19380be528d);}

}])
//# sourceMappingURL=sourcemaps/423c241d2f17020d.js.map