(globalThis["webpackChunk_canva_web"] = globalThis["webpackChunk_canva_web"] || []).push([[81090],{

/***/ 839452:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);__web_req__(487867);__web_req__(270937);__web_req__(16433);globalThis._456c437108d2d2713799e19380be528d = globalThis._456c437108d2d2713799e19380be528d || {};(function(__c) {var Ph=__c.Ph;var Lb=__c.Lb;var vb=__c.vb;var MOc,QOc,ROc,SOc,TOc,UOc,VOc,WOc,XOc,ZOc,NOc,$Oc,aPc,YI,ZI;MOc=function(a){switch(a){case 1:return"(min-width: 600px)";case 2:return"(min-width: 900px)";case 3:return"(min-width: 1200px)";case 4:return"(min-width: 1650px)";default:return"(max-width: 599px)"}};
__c.OOc=function(a){const {alt:b,sources:c,className:d,ref:e,...f}=a,g=(0,__c.db)(()=>c.sort((k,l)=>k.nl&&l.nl?NOc[l.nl]-NOc[k.nl]:k.nl?l.nl?0:-1:1).map(k=>{const l=k.nl;k=k.images.map(q=>({src:q.src,size:q.Dw,unit:"w"}));const m=__c.oha(k);return{media:MOc(l),Pyd:k,srcSet:m}}),[c]);a=(0,__c.db)(()=>__c.pha(g.flatMap(k=>k.Pyd),f.src),[f.src,g]);return(0,__c.Ed)("picture",{ref:e,className:"DcyBDA",children:[g.map(({media:k,srcSet:l})=>(0,__c.E)("source",{media:k,srcSet:l},l)),(0,__c.E)("img",{...f,
src:a,alt:b,className:d})]})};__c.POc=function(a){a=__c.CMc(a);const b=__c.CMc("#ffffff");return a>b?(a+.05)/(b+.05):(b+.05)/(a+.05)};QOc=function({x:a,y:b}){return Math.sqrt(a**2+b**2)};ROc=function({x:a,y:b},{x:c,y:d}){return QOc({x:c-a,y:d-b})};SOc=function(a,b,c){c={x:c.x-b.x,y:b.y-c.y};a={x:a.x-b.x,y:b.y-a.y};return Math.acos((c.x*a.x+c.y*a.y)/(QOc(c)*QOc(a)))};
TOc=function(a,b){const c=new Float32Array(9),d=a[0],e=a[1],f=a[2],g=a[3],k=a[4],l=a[5],m=a[6],q=a[7];a=a[8];const t=b[0],v=b[1],y=b[2],z=b[3],A=b[4],C=b[5],F=b[6],G=b[7];b=b[8];c[0]=t*d+z*e+F*f;c[1]=v*d+A*e+G*f;c[2]=y*d+C*e+b*f;c[3]=t*g+z*k+F*l;c[4]=v*g+A*k+G*l;c[5]=y*g+C*k+b*l;c[6]=t*m+z*q+F*a;c[7]=v*m+A*q+G*a;c[8]=y*m+C*q+b*a;return c};UOc=function(a,b){return new Float32Array([a[0]*b[0]+a[1]*b[1]+a[2]*b[2],a[3]*b[0]+a[4]*b[1]+a[5]*b[2],a[6]*b[0]+a[7]*b[1]+a[8]*b[2]])};
VOc=function(a){return new Float32Array([a[4]*a[8]-a[5]*a[7],a[2]*a[7]-a[1]*a[8],a[1]*a[5]-a[2]*a[4],a[5]*a[6]-a[3]*a[8],a[0]*a[8]-a[2]*a[6],a[2]*a[3]-a[0]*a[5],a[3]*a[7]-a[4]*a[6],a[1]*a[6]-a[0]*a[7],a[0]*a[4]-a[1]*a[3]])};WOc=function(a,b,c,d,e,f,g,k){a=new Float32Array([a,c,e,b,d,f,1,1,1]);g=UOc(VOc(a),new Float32Array([g,k,1]));return TOc(a,new Float32Array([g[0],0,0,0,g[1],0,0,0,g[2]]))};
XOc=function({L3b:a,background:b=!1,autoplay:c=!1,Lo:d=!1,loop:e=!1,BAe:f=!1,AY:g=!1}){a=new URL(`${"https://player.vimeo.com"}/video/${a}`);a.searchParams.append("background",String(b));a.searchParams.append("autoplay",String(c));a.searchParams.append("muted",String(d));a.searchParams.append("loop",String(e));a.searchParams.append("autopause",String(f));a.searchParams.append("dnt","true");a.searchParams.append("controls",String(!g));return a.toString()};
ZOc=function(a){return a?(a=YOc.get(a))?a:"fill-parent":"fill-parent"};NOc={[0]:0,[1]:1,[2]:2,[3]:3,[4]:4};$Oc=__webpack_require__(296713);aPc=$Oc.Fragment;YI=$Oc.jsx;ZI=$Oc.jsxs;var $I=__webpack_require__(978109),aJ=$I.Component,bPc=$I.createRef,bJ=$I.memo,cPc=$I.useContext,dPc=$I.useEffect,ePc=$I.useMemo,fPc=$I.useRef,gPc=$I.useState;var hPc=__webpack_require__,iPc=hPc(208463),cJ=hPc.n_x(iPc)();var dJ=__webpack_require__(549056)._;var eJ=__webpack_require__(186901),fJ=eJ.EW,jPc=eJ.h5,gJ=eJ.sH,hJ=eJ.XI,kPc=eJ.z7;var iJ=__webpack_require__(621369)._;var lPc=__webpack_require__(270531),mPc=lPc.nu,nPc=lPc.PA;var oPc=__webpack_require__(594314).A;var pPc=__webpack_require__(245307).Fm;var qPc=class{anc(){const a=this.tB;return[`translateX(${a.Qqb}px)`,`translateY(${a.Rqb}px)`,`rotate(${a.rotate}rad)`,`scaleX(${a.scaleX})`,`scaleY(${a.scaleY})`].join(" ")}constructor(a,b){this.tB={rotate:-Math.atan2(b.topLeft.y-b.topRight.y,b.topRight.x-b.topLeft.x),scaleX:ROc(b.topLeft,b.topRight)/ROc(a.topLeft,a.topRight),scaleY:ROc(b.topLeft,b.bottomLeft)/ROc(a.topLeft,a.bottomLeft),Qqb:b.topLeft.x-a.topLeft.x,Rqb:b.topLeft.y-a.topLeft.y}}};var rPc=class{anc(){const a=this.matrix;return`matrix3d(${[a[0],a[3],0,a[6],a[1],a[4],0,a[7],0,0,1,0,a[2],a[5],0,a[8]].join()})`}transformPoint(a){a=new Float32Array([a.x,a.y,1]);a=UOc(this.matrix,a);return{x:a[0]/a[2],y:a[1]/a[2]}}constructor(a,b){a=WOc(a.topLeft.x,a.topLeft.y,a.topRight.x,a.topRight.y,a.bottomRight.x,a.bottomRight.y,a.bottomLeft.x,a.bottomLeft.y);b=WOc(b.topLeft.x,b.topLeft.y,b.topRight.x,b.topRight.y,b.bottomRight.x,b.bottomRight.y,b.bottomLeft.x,b.bottomLeft.y);b=TOc(b,VOc(a));
for(a=0;a!==9;a++)b[a]/=b[8];this.matrix=b}};var sPc=(a,b,c)=>{if(!(a.width&&a.height&&b.width&&b.height))return null;a={topLeft:{x:0,y:0},topRight:{x:a.width,y:0},bottomRight:{x:a.width,y:a.height},bottomLeft:{x:0,y:a.height}};b={topLeft:{x:b.width*c.topLeft.x,y:b.height*c.topLeft.y},topRight:{x:b.width*c.topRight.x,y:b.height*c.topRight.y},bottomRight:{x:b.width*c.bottomRight.x,y:b.height*c.bottomRight.y},bottomLeft:{x:b.width*c.bottomLeft.x,y:b.height*c.bottomLeft.y}};return[SOc(b.bottomLeft,b.topLeft,b.topRight),SOc(b.topLeft,b.topRight,
b.bottomRight),SOc(b.topLeft,b.bottomLeft,b.bottomRight),SOc(b.bottomLeft,b.bottomRight,b.topRight)].every(d=>Math.abs(d-Math.PI/2)<=Math.PI/720)?new qPc(a,b):new rPc(a,b)};var tPc=({children:a,Tk:b,mA:c,ljd:d,ejd:e,UCa:f})=>{const g=ePc(()=>sPc({width:d,height:e},{width:b,height:c},f)?.anc(),[c,b,f,e,d]);return g?YI("div",{className:"ntUmVA",style:{transform:g},children:YI("div",{className:"pIg6rA",style:{width:d,height:e},children:a})}):null};var uPc,vPc,wPc,xPc=bJ(({children:a,className:b,width:c,height:d})=>YI("div",{className:b,style:{width:c,height:d},children:a})),yPc;
new (uPc=class extends dJ{constructor(){super(yPc);vPc()}},(()=>{class a extends(wPc=aJ){static F(b){vb(b,{r3:fJ,scale:fJ,Fba:fJ,gxa:fJ,UCa:fJ})}get r3(){return this.props.Fba==null?{width:400,height:300}:{width:this.props.Fba.width,height:this.props.Fba.height}}get scale(){const b=this.props.fit;return b==null||b.value==null?1:b.value/(b.direction==="width"?this.r3.width:this.r3.height)}get Fba(){return{width:this.r3.width*this.scale,height:this.r3.height*this.scale}}get gxa(){const b=this.props.gxa;
return{width:b.width*this.scale,height:b.height*this.scale}}get UCa(){const b=this.props.gxa.Q$a;if(b!=null)return{topLeft:zPc(b.topLeft),topRight:zPc(b.topRight),bottomRight:zPc(b.bottomRight),bottomLeft:zPc(b.bottomLeft)}}render(){const {Gsb:b=xPc,AZc:c,flip:d=!1}=this.props;return YI(b,{className:cJ("AN7ZxA",{QedALA:d}),height:this.Fba.height,width:this.Fba.width,children:YI("div",{className:this.UCa?"_2aAdg":"StRNEQ",children:this.UCa?YI(tPc,{Tk:this.Fba.width,mA:this.Fba.height,ljd:this.gxa.width,
ejd:this.gxa.height,UCa:this.UCa,children:YI(c,{className:cJ("h2EMkQ",{QedALA:d}),...this.gxa})}):YI(c,{className:cJ("alxWXw",{QedALA:d})})})})}constructor(...b){super(...b);a.F(this)}}({c:[yPc,vPc]}=iJ(a,[],[Lb],wPc))})(),uPc);var zPc=({top:a,left:b})=>({x:b,y:a});var APc,BPc,CPc,DPc;
new (APc=class extends dJ{constructor(){super(DPc);BPc()}},(()=>{class a extends(CPc=aJ){static F(b){vb(b,{Skb:gJ.ref,fit:fJ})}render(){const b=this.props.Ab;return b?YI(__c.il,{Ab:b,Ds:!0,children:({ref:c,visible:d})=>d?YI(this.c5b,{}):YI("div",{ref:c,className:"_8Hj4jQ"})}):YI(this.c5b,{})}get fit(){const {Db:b,fit:c,maxWidth:d=Infinity,maxHeight:e=Infinity}=this.props;if(c){var {yb:f}=b.TD[0],{width:g,height:k}=f[0];return{direction:c.direction,value:c?.direction==="height"?Math.min(this.Skb?.height??
k,e):Math.min(this.Skb?.width??g,d)}}}constructor(...b){super(...b);this.Skb=(DPc.F(this),void 0);this.ANd=__c.ib(hJ(c=>{(c=c.offset)&&c.width>0&&c.height>0&&(this.Skb=c)}),200,{leading:!0});this.c5b=()=>{var c=this.props.Db;const d=this.props.REa,{yb:e,SC:f}=c.TD[0],{width:g,height:k}=e[0],l=(c=c.oG[0])&&{width:c.width,height:c.height},m={width:g,height:k,Q$a:f};return YI(oPc,{offset:!0,onResize:this.ANd,children:({measureRef:q})=>YI(mPc,{children:()=>YI("div",{ref:q,className:"M3NDYw",children:YI(yPc,
{Fba:l,gxa:m,Gsb:this.Gsb,AZc:this.FXc,flip:d,fit:this.fit})})})})};this.Gsb=({className:c,width:d,height:e,children:f})=>{const g=this.props.Db,k=g.oG[0],l=k?.url;var m;if(m=k?.mimeType)a:switch(m=k.mimeType,m){case 1:m="image/avif";break a;default:throw new __c.n(m);}const q=g.Frd?.url??l;return ZI("div",{className:cJ(c,"QDpgzQ"),style:{width:d,height:e},children:[k&&ZI("picture",{children:[m&&YI("source",{srcSet:l,type:m}),YI("img",{alt:g.altText||"",src:q,style:{width:d,height:e},onLoad:this.props.eMd})]}),
f]})};this.FXc=({className:c,width:d,height:e})=>{const {yb:f,q9a:g}=this.props.Db.TD[0];var k=g?`${g.Au*100}%/${g.vertical*100}%`:void 0;const {url:l}=f[0];return YI("img",{alt:this.props.Db.altText||"",className:c,style:{width:d,height:e,borderRadius:k},src:l,draggable:!1})}}}({c:[DPc,BPc]}=iJ(a,[],[Lb],CPc))})(),APc);var EPc,FPc,GPc,jJ;
new (EPc=class extends dJ{constructor(){super(jJ);FPc()}},(()=>{class a extends(GPc=aJ){static F(b){vb(b,{currentSrc:gJ.ref,playbackTime:gJ.ref,Rva:gJ.ref})}get Pza(){if(!this.ref.current)return 0;const b=this.ref.current.duration-this.ref.current.currentTime;return isNaN(b)?0:b}start(b){const c=()=>{this.ref.current&&(this.ref.current.currentTime=this.playbackTime,(this.ulb=this.ref.current.play())?this.ulb.then(pPc.wrap(()=>{this.props.onTimeUpdate?.(this.Pza);this.props.onPlay?.();this.props.MP?.()}),
pPc.wrap(d=>{this.props.SD?.(d)})):(this.props.onTimeUpdate?.(this.Pza),this.props.onPlay?.()))};b=b.navigator?.userAgent??"";!b.match(/AppleWebKit\//)||b.match(/(Chrome|Chromium)\//)||this.efb?c():setTimeout(pPc.wrap(c),0);this.efb=!0}stop(){const b=this.ulb;b?.then(()=>{this.ref.current&&!this.ref.current.paused&&b===this.ulb&&(this.ref.current.pause(),this.ref.current.load(),this.props.onCancel?.())},()=>{})}componentDidMount(){jPc(()=>this.currentSrc=this.Qmc());this.ref.current&&(this.ref.current.volume=
.8)}componentDidUpdate(b){const c=this.v5c(b.srcSet??[],this.props.srcSet??[]);if(b.src!==this.props.src||b.Lo!==this.props.Lo||!c){const e=this.Qmc();if(e!==this.currentSrc){jPc(()=>{this.currentSrc=e;this.efb=!1;this.playbackTime=c&&this.ref.current?this.ref.current.currentTime:0});return}}const d=b.play&&this.efb;this.props.play&&!d&&this.start(window);b.play&&!this.props.play&&this.stop()}componentWillUnmount(){this.stop()}render(){const {src:b,poster:c,title:d,fka:e=!1,AY:f=!0,Lo:g=!0,loop:k=
!0}=this.props;return YI(__c.rNa,{ref:this.ref,src:this.currentSrc??b,style:{backgroundImage:e?void 0:`url(${c})`},poster:e?void 0:c,className:"_5W0ung",title:d,controls:!f,loop:k,muted:g,playsInline:!0,preload:"none",onTimeUpdate:this.onTimeUpdate,onLoadedData:this.props.yC})}constructor(...b){super(...b);this.currentSrc=(jJ.F(this),void 0);this.playbackTime=0;this.Rva=void 0;this.efb=!1;this.ref=bPc();this.onTimeUpdate=()=>{this.props.onTimeUpdate?.(this.Pza)};this.Qmc=()=>{var c=window.devicePixelRatio;
const d=this.ref.current?.getBoundingClientRect().width;if(d==null||!this.props.srcSet?.length)return this.props.src;c*=d;if(this.Rva&&this.Rva.width>=c&&this.props.srcSet.find(f=>f.url===this.Rva.url)&&(!this.props.Lo&&this.Rva.hasAudio||this.props.Lo))return this.Rva.url;const e=this.props.Lo===!1?__c.mNc(this.props.srcSet,c):__c.FI(this.props.srcSet,c);e&&jPc(()=>{this.Rva=e});return e?.url};this.v5c=(c,d)=>c.length===d.length&&c.every(({url:e},f)=>e===d[f].url)}}({c:[jJ,FPc]}=iJ(a,[],[Lb],GPc))})(),
EPc);var HPc,IPc,JPc,KPc;
new (HPc=class extends dJ{constructor(){super(KPc);IPc()}},(()=>{class a extends(JPc=aJ){static F(b){vb(b,{Pza:gJ.ref,isPlaying:gJ.ref,Flc:fJ,Dnc:hJ,BFa:hJ,jrb:hJ})}get Flc(){return this.isPlaying?__c.qNc(this.Pza,"medium"):void 0}render(){return ZI(__c.Tf,{className:"zOgBGg",children:[YI(jJ,{...this.props,onPlay:this.Dnc,onCancel:this.BFa,onTimeUpdate:this.jrb}),YI(this.IAa,{})]})}constructor(...b){super(...b);this.Pza=(KPc.F(this),0);this.isPlaying=!1;this.Dnc=()=>{this.isPlaying=!0};this.BFa=()=>
{this.isPlaying=!1};this.jrb=c=>{this.Pza=c};this.IAa=nPc(()=>YI(__c.Uf,{location:"bottom-start",children:YI(__c.Lk,{tone:"contrast",icon:YI(__c.vOc,{size:"small"}),text:this.Flc})}))}}({c:[KPc,IPc]}=iJ(a,[],[Lb],JPc))})(),HPc);var MPc=bJ(({play:a,aspectRatio:b,title:c=__c.J("7hydPA"),...d})=>{const e=fPc(null),[f,g]=gPc(!1);d=XOc(d);dPc(()=>{f&&a!=null&&e.current?.contentWindow?.postMessage({method:a?"play":"pause"},"https://player.vimeo.com")},[a,f]);const k=fPc(a);k.current=a;dPc(()=>{const l=m=>{m.origin.startsWith("https://player.vimeo.com")&&e.current?.contentWindow===m.source&&(typeof m.data==="string"?JSON.parse(m.data):m.data).event==="ready"&&(g(!0),k.current!=null&&e.current?.contentWindow?.postMessage({method:k.current?
"play":"pause"},"https://player.vimeo.com"))};window?.addEventListener("message",l);return()=>{window?.removeEventListener("message",l)}},[]);c=YI(LPc,{src:d,title:c,ref:e});return(b=b&&__c.BOc.get(b))?YI(__c.ll,{ratio:b,children:c}):c}),LPc=({src:a,title:b,ref:c})=>YI("iframe",{src:a,ref:c,className:"Nt7f9A",frameBorder:0,title:b});var NPc=a=>a.rQ?YI(KPc,{...a}):YI(jJ,{...a}),OPc=bJ(({model:a,play:b=!0,SD:c,MP:d,yC:e,rQ:f=!1,title:g,fka:k,Lo:l=!0})=>{b=a.autoplay!=null?a.autoplay&&b:b;switch(a.type){case "YOUTUBE_SOURCE":return YI(__c.FOc,{Ri:a.Ri,mode:"inline",autoplay:b,loop:a.loop,Lo:a.Lo??l,AY:a.AY,aspectRatio:ZOc(a.aspectRatio)});case "VIMEO_SOURCE":return YI(aPc,{children:!k&&YI(MPc,{L3b:a.Ri,aspectRatio:ZOc(a.xqa),play:b,loop:a.loop,Lo:a.Lo??l,AY:a.AY,title:g})});case "STATIC_VIDEO_SOURCE":return a={src:__c.FI(a.CB,Infinity)?.url,
srcSet:a.CB,poster:__c.FI(a.yb)?.url,play:b,SD:c,MP:d,yC:e,title:g,fka:k,loop:a.loop,Lo:a.Lo??l,AY:a.AY},ZI("div",{className:"iaIdcQ",children:[!k&&YI(__c.zI,{src:a.poster,alt:a.title,className:"_5W0ung"}),b?YI(NPc,{...a,rQ:f}):null]});default:throw new __c.n(a);}}),YOc=new Map([[1,"1:1"],[2,"4:3"],[3,"5:2"],[4,"16:9"],[5,"16:10"],[6,"20:13"]]);var PPc,QPc,RPc,SPc;
new (PPc=class extends dJ{constructor(){super(SPc);QPc()}},(()=>{class a extends(RPc=aJ){static F(b){vb(b,{r3:fJ,Mzc:fJ,Ozc:fJ})}get r3(){return this.props.context==null?{width:400,height:300}:{width:this.props.context.width,height:this.props.context.height}}get Mzc(){return{paddingBottom:`${this.r3.height/this.r3.width*100}%`}}get Ozc(){const b=this.props.rPd;return{top:`${b.topLeft.top*100}%`,left:`${b.topLeft.left*100}%`,right:`${(1-b.bottomRight.left)*100}%`,bottom:`${(1-b.bottomRight.top)*100}%`}}render(){const b=
this.props.context;return YI("div",{style:{backgroundImage:b&&`url(${b.url})`,maxWidth:this.r3.width,maxHeight:this.r3.height},className:"cBcKAA",children:YI("div",{className:"_7x30CA",style:this.Mzc,children:YI("div",{className:"J2LaPw",style:this.Ozc,children:this.props.overlay})})})}constructor(...b){super(...b);a.F(this)}}({c:[SPc,QPc]}=iJ(a,[],[Lb],RPc))})(),PPc);var TPc=a=>{const b=a.Db;a=a.Ab;const c=YI(OPc,{model:b.J3b,title:b.altText}),d=YI(SPc,{context:b.oG[0],rPd:b.gDc,overlay:c});return a?YI(__c.il,{Ab:a,Ds:!0,children:({ref:e,visible:f})=>f?d:YI("div",{className:"_3hw80A",ref:e})}):d};var UPc=({Db:a,Ab:b})=>{const c=ePc(()=>a.pj.map(e=>({src:e.url,height:e.height,width:e.width})),[a.pj]),d=YI(__c.NNc,{Mza:c,backgroundColor:a.backgroundColor});return b?YI(__c.il,{Ab:b,Ds:!0,children:({ref:e,visible:f})=>YI(__c.yd,{height:"full",width:"full",ref:e,children:f?d:null})}):YI(__c.yd,{height:"full",width:"full",children:d})};var VPc=({Db:a,Ab:b})=>{const c=ePc(()=>a.pj.map(g=>({jm:g.url,height:g.height,width:g.width})),[a.pj]),d=ePc(()=>c.map(g=>g.width/g.height).reduce((g,k)=>g+k,0)/c.length,[c]),e=__c.ld({alpha:{light:1,dark:.25}})?.alpha||1,f=YI(__c.RNc,{pj:c,Kwc:d>2?2:3,GId:5,backgroundColor:a.backgroundColor?__c.Ye(a.backgroundColor):void 0,Qqa:e,Nad:{default:"1u",pb:"1.5u"}});return b?YI(__c.il,{Ab:b,Ds:!0,children:({ref:g,visible:k})=>YI("div",{ref:g,className:"LARHyQ",children:k?f:null})}):YI("div",{className:"LARHyQ",
children:f})};var WPc,XPc,YPc,ZPc;
new (WPc=class extends dJ{constructor(){super(ZPc);XPc()}},(()=>{class a extends(YPc=aJ){static F(b){vb(b,{fka:gJ.ref,GZb:gJ.ref,backgroundColor:fJ,onLoad:hJ})}get backgroundColor(){const {backgroundColor:b,Qqa:c=1,Vcb:d,Pdb:e}=this.props;if(e)return d;const f=b?__c.Ye(b):void 0,g=f&&new __c.gf(f.r,f.g,f.b,c);if(f)return this.GZb?d:g?.bNa()}componentDidMount(){this.props.jt&&__c.Gb(this,kPc(()=>!this.props.jt,()=>this.fka=!1))}get paddingBottom(){const b=this.props.fit;return b?.direction==="width"&&
b.aspectRatio?`${b.aspectRatio*100}%`:void 0}get width(){const b=this.props.fit;if(b?.direction==="width"&&b.value)return b.value;if(b?.direction==="height"&&b.aspectRatio)return __c.na(b.value!=null,"A fit.value must be given when fit.aspectRatio is defined\n      and fit.direction == 'height' in Preview component"),b.value/b.aspectRatio}render(){const b=this.props.children,c=this.props.fit;return YI("div",{style:{backgroundColor:this.backgroundColor,paddingBottom:this.paddingBottom,width:this.width},
className:cJ("_6IqfkA",this.props.AL&&"AApK3w",c?.aspectRatio&&"NDUnxQ",c?.direction==="width"&&"ym6shw",c?.direction==="height"&&"UzmnKQ",c?.direction==="cover"&&"_5ot2Iw",this.props.p0&&"LUSBfA",Ph.Pb&&"hvE3zQ"),children:YI("div",{className:cJ("_6pE9kQ",this.fka&&"zjFmOA"),children:b({onLoad:this.onLoad})})})}constructor(b){super(b);this.fka=(ZPc.F(this),void 0);this.onLoad=()=>{this.GZb=!0};this.fka=!!this.props.jt;this.GZb=!1}}({c:[ZPc,XPc]}=iJ(a,[],[Lb],YPc))})(),WPc);var $Pc,aQc,bQc,kJ;
new ($Pc=class extends dJ{constructor(){super(kJ);aQc()}},(()=>{class a extends(bQc=aJ){static F(b){vb(b,{Jfb:gJ.ref,onLoad:hJ.bound})}componentDidMount(){const b=this.Uua.current;b?.complete&&b.naturalHeight!==0&&jPc(()=>this.Jfb=!0)}onLoad(){this.Jfb=!0;this.props.onLoad?.()}render(){const {Ab:b,lazy:c=!0}=this.props;return c&&b!=null?YI(this.dYc,{}):YI(this.sZc,{})}constructor(...b){super(...b);this.Jfb=(kJ.F(this),!1);this.Uua=bPc();this.sZc=()=>{const c=this.props.Image;return YI("div",{className:cJ("pJ2y0g",
"p_VKTA",this.props.className),children:YI(c,{visible:!0,onLoad:this.onLoad})})};this.dYc=()=>{const c=this.props.Image,d=this.props.className,e=__c.h(this.props.Ab);return YI(__c.il,{Ab:e,Ds:!0,children:({ref:f,visible:g})=>YI(mPc,{children:()=>ZI("div",{ref:f,className:cJ("pJ2y0g","p_VKTA",{VVUDbQ:Ph.Pb,CW2h7Q:!this.Jfb},d),children:[YI(c,{Uua:this.Uua,visible:g,onLoad:this.onLoad}),YI("noscript",{children:YI(c,{visible:!0})})]})})})}}}({c:[kJ,aQc]}=iJ(a,[],[Lb],bQc))})(),$Pc);var cQc,dQc,eQc,fQc;
new (cQc=class extends dJ{constructor(){super(fQc);dQc()}},(()=>{class a extends(eQc=aJ){static F(b){vb(b,{sources:fJ})}get sources(){return gQc(this.props.Db.lW)}render(){return YI(kJ,{lazy:this.props.lazy,Ab:this.props.Ab,Image:this.Image})}constructor(...b){super(...b);this.Image=(fQc.F(this),nPc(({Uua:c,visible:d,onLoad:e})=>{const f=this.props.Db,g=this.props.fit,k=this.props.maxHeight,l=this.props.maxWidth,m=this.props.altText;return YI(__c.OOc,{ref:c,onLoad:e,sources:d?this.sources:[],className:cJ({ETO4HA:g===
"width",pJP5ZQ:g==="height",xQIFqw:g==="cover"}),style:{maxHeight:k,maxWidth:l},alt:m||f.altText||"",draggable:!1})}))}}({c:[fQc,dQc]}=iJ(a,[],[Lb],eQc))})(),cQc);var hQc=a=>a.map(b=>({src:b.url,Dw:b.width})),gQc=a=>a.map(b=>({nl:b.nl===1?1:0,images:hQc(b.yb)}));var iQc,jQc,kQc,lQc;
new (iQc=class extends dJ{constructor(){super(lQc);jQc()}},(()=>{class a extends(kQc=aJ){static F(b){vb(b,{sources:fJ,sizes:fJ})}get sources(){return this.props.Db.yb.map(b=>({src:b.url,Dw:b.width}))}get sizes(){return(this.props.sizes??[]).map(({nl:b,DPc:c})=>({nl:b?{value:b,type:"px"}:void 0,width:{value:c,type:"vw"}}))}render(){return YI(kJ,{lazy:this.props.lazy,Ab:this.props.Ab,Image:this.Image,onLoad:this.props.onLoad})}constructor(...b){super(...b);this.Image=(lQc.F(this),nPc(({Uua:c,visible:d,
onLoad:e})=>{const f=this.props.Db,g=this.props.fit,k=this.props.maxHeight,l=this.props.maxWidth,m=this.props.altText,q=this.props.onError;return YI(__c.Dd,{ref:c,onLoad:e,onError:t=>q?.(t.currentTarget.src),sources:d?this.sources:[],sizes:this.sizes,className:cJ({w3KZWA:g==="width",AiHWyw:g==="height",_4iDt8g:g==="cover"}),style:{maxHeight:k,maxWidth:l},alt:m||f.altText||"",draggable:!1})}))}}({c:[lQc,jQc]}=iJ(a,[],[Lb],kQc))})(),iQc);var mQc,nQc,oQc,pQc;
new (mQc=class extends dJ{constructor(){super(pQc);nQc()}},(()=>{class a extends(oQc=aJ){static F(b){vb(b,{play:gJ.ref,O2a:gJ.ref,Cp:hJ.bound})}Cp(b){this.play=b;this.O2a=!0}render(){const b=this.props.Ab;return b?YI(__c.il,{Ab:b,Cp:this.Cp,children:({ref:c})=>YI(mPc,{children:()=>YI("div",{ref:c,className:cJ("CuOmfw",{hNh2VA:Ph.Pb,_5_F_aA:!this.O2a}),children:YI(this.j7b,{})})})}):YI(this.j7b,{})}constructor(b){super(b);this.play=(pQc.F(this),!1);this.O2a=!1;this.j7b=nPc(()=>{const {n2c:e,maxHeight:f,
maxWidth:g,Db:{Br:k,altText:l},rQ:m=!1,autoPlay:q=!0,SD:t,MP:v,yC:y,Lo:z=!0}=this.props;return YI("div",{className:"_hGIGQ",style:{maxHeight:f,maxWidth:g},children:YI(e,{model:k,play:q&&this.play,SD:t,MP:v,yC:y,rQ:m,title:l,fka:!this.O2a,Lo:z})})});const {Ab:c,lazy:d=!0}=this.props;this.play=!c;this.O2a=!d||!c}}({c:[pQc,nQc]}=iJ(a,[],[Lb],oQc))})(),mQc);
var qQc=function(a){return b=>{const c=cPc(__c.bfb),{C2:d}=cPc(__c.Seb);return YI(a,{...b,autoPlay:!(c&&d!==2)&&b.autoPlay})}}(bJ(a=>YI(pQc,{...a,n2c:OPc})));var rQc;__c.lJ=({model:a,play:b,active:c=!1,Lo:d=!0,SD:e,MP:f,yC:g,rQ:k,lazy:l,Ab:m,fit:q,REa:t,maxWidth:v,maxHeight:y,sizes:z,altText:A,background:C,Qqa:F,jt:G,AL:I,Vcb:L="#F8F9F9",Pdb:O=!1,onError:P})=>YI(ZPc,{fit:q,backgroundColor:C!=="none"?a.backgroundColor:void 0,Qqa:F,p0:C==="gradient",Vcb:L,Pdb:O,jt:G,AL:I,children:({onLoad:R})=>YI(rQc,{model:a,play:b,active:c,Lo:d,SD:e,MP:f,yC:g,lazy:l,Ab:m,fit:q,REa:t,maxWidth:v,maxHeight:y,sizes:z,altText:A,onLoad:R,onError:P,rQ:k})});
rQc=bJ(({model:a,play:b,active:c,Lo:d,SD:e,MP:f,yC:g,lazy:k,Ab:l,fit:m,REa:q,maxWidth:t,maxHeight:v,sizes:y,altText:z,onLoad:A,onError:C,rQ:F})=>{switch(a.type){case "CONTEXTUAL":return YI(DPc,{Db:a,fit:m&&m?.direction!=="cover"?{...m,direction:m.direction}:void 0,maxHeight:v,maxWidth:t,REa:q,Ab:l,eMd:A});case "CONTEXTUAL_VIDEO":return YI(TPc,{Db:a,fit:m&&m?.direction!=="cover"?{...m,direction:m.direction}:void 0,REa:q,Ab:l});case "SINGLE_IMAGE":return YI(lQc,{Db:a,lazy:k,Ab:l,fit:m?.direction,maxHeight:v,
maxWidth:t,sizes:y,altText:z,onLoad:A,onError:C});case "VIDEO":return YI(qQc,{Db:a,autoPlay:b==="always"&&__c.Af({Xf:__c.Va(Ph.Xf),Pb:Ph.Pb})||c,Lo:d,SD:e,yC:g,MP:f,rQ:F&&b==="on-active",maxWidth:t,maxHeight:v,lazy:k,Ab:l});case "RESPONSIVE_IMAGE":return YI(fQc,{Db:a,lazy:k,Ab:l,fit:m?.direction,maxHeight:v,maxWidth:t,sizes:y,altText:z,onLoad:A});case "GALLERY":return YI(VPc,{Db:a,Ab:l});case "DIAGONAL_OVERLAP":return YI(UPc,{Db:a,Ab:l});case "DESIGN":throw Error(`Preview type ${a.type} is not implemented in Preview`);
default:throw new __c.n(a);}});
}).call(globalThis, globalThis._456c437108d2d2713799e19380be528d);}

}])
//# sourceMappingURL=sourcemaps/4db37808d0e2d42c.js.map