(globalThis["webpackChunk_canva_web"] = globalThis["webpackChunk_canva_web"] || []).push([[40089],{

/***/ 510344:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);__web_req__(150235);__web_req__(270937);__web_req__(839452);__web_req__(119517);__web_req__(16433);__web_req__(487867);__web_req__(737068);__web_req__(827954);__web_req__(278042);__web_req__(736360);globalThis._456c437108d2d2713799e19380be528d = globalThis._456c437108d2d2713799e19380be528d || {};(function(__c) {var yd=__c.yd;var K=__c.K;var qe=__c.qe;var Yj=__c.Yj;var Sj=__c.Sj;var Ig=__c.Ig;var Ye=__c.Ye;
var qig=function(a){return`rgb(${Math.round(a.r)},${Math.round(a.g)},${Math.round(a.b)})`},sig=function({s4:a}){return{cRc:({model:b})=>NT(rig,{title:b.title,subtitle:b.subtitle,yQ:b.yQ?.Vs,s4:b.djc?a:void 0})}},tig=function(){return{Dsb:OT(({model:a})=>{const b=a.backgroundColor?Ye(a.backgroundColor):void 0,c=a.pj.map(d=>({jm:d.url,width:d.width,height:d.height}));return NT(Ig,{$a:"COLLECTION_BANNER_HEADER",children:NT(__c.SNc,{title:a.title??"",description:a.subtitle,backgroundColor:b,pj:c,JLc:a.columns})})})}},
wig=function({Pq:a,$Vb:b}){const c=({Hvc:d,...e})=>PT(uig,{children:[NT(Sj,{GL:"small",children:NT(a,{...e,action:{...e.action,label:d??e.action.label}})}),NT(Sj,{cA:"small",children:NT(a,{...e})})]});return{ASc:({model:d})=>{var e=d.title,f=d.Pib,g=d.subtitle,k=d.yQ?.Vs,l=d.Ua,m=d.style;if(d.action){var q=d.action;if(d.Kvb)a:{var t=d.Kvb;switch(t){case 1:t="primary";break a;case 2:t="neutral";break a;default:throw new __c.n(t);}}else t="primary";d=NT(c,{action:q,align:"center",variant:t,Hvc:d.Cvc})}else d=
void 0;return NT(vig,{title:e,Pib:f,subtitle:g,yQ:k,Db:l,Ghd:m,Qqa:.25,button:d,$Vb:b??!1})}}},Big=function({Pq:a}){return{vRc:OT(({model:b,oK:c})=>{const d=()=>NT(Yj,{size:qe({default:"large",pb:"xlarge"}),nb:"legacy",className:"C1jp7g",tagName:c?"h2":"h1",alignment:"center",children:b.title}),e=()=>NT(K,{size:qe({default:"medium",pb:"large"}),nb:"legacy",alignment:"center",children:b.subtitle}),f=()=>b.fi?NT("div",{className:"nIs3fA",children:NT(a,{action:b.fi,stretch:!1,align:"center",variant:"primary"})}):
null,g=()=>b.Uv?NT("div",{className:"nIs3fA",children:NT(a,{action:b.Uv,stretch:!1,variant:"secondary"})}):null;let k;switch(b.background?.type){case "RESPONSIVE_IMAGE":var l=xig(b.background.lW);k=l.length?NT(__c.OOc,{sources:l,className:"BS5N6g",alt:b.background?.altText||"",draggable:!1}):void 0;break;case "SINGLE_IMAGE":l=yig(b.background.yb);k=l.length?NT(__c.Dd,{sources:l,sizes:[],className:"BS5N6g",alt:b.background?.altText||"",draggable:!1}):void 0;break;default:throw Error(`Image type: ${b.background?.type} is unsupported for CTABanner`);
}const m=()=>NT(zig,{dj:b.title?d:void 0,ST:e,Ytb:f,p0c:g,s4c:c?"end":"start"}),q=b.background?.backgroundColor?Ye(b.background.backgroundColor).JN():void 0;l=q?__c.POc(q):void 0;l=k?b.h3b?"dark":"light":l?l<7?"light":"dark":void 0;return NT(Ig,{$a:"CTA_BANNER_HEADER",children:NT(__c.Od,{light:l,dark:l,pn:l,nx:l,children:t=>NT("div",{className:t.className,children:NT(Aig,{VQc:k,backgroundColor:q,p1c:m,oK:c||!1})})})})})}},Dig=function({Pq:a,tda:b}){return{pWc:OT(({model:c,oK:d})=>{var e=c.foreground;
if(e.type!=="SINGLE_IMAGE")throw Error("Horizontal banner only supports single image previews");var f=__c.h(e.backgroundColor,"Horizontal banner foreground must have background colour");const g=Ye(f).JN();f=e.yb.map(t=>({src:t.url,Dw:t.width}));const k=NT(__c.lJ,{model:e,fit:{direction:"width",aspectRatio:__c.Ebf(e)},play:"never"}),l=NT(__c.Dd,{sources:f,sizes:[],alt:e.altText||"",className:"_8BGnJQ"}),m=c.fi?NT(a,{action:c.fi,variant:"primary"}):void 0,q=c.Uv?NT(a,{action:c.Uv,variant:"secondary"}):
void 0;e=g?__c.POc(g):void 0;e=qe({default:void 0,Mc:e?e<7?"light":"dark":void 0});return NT(Ig,{$a:"HORIZONTAL_BANNER_HEADER",children:NT(__c.Od,{light:e,dark:e,pn:e,nx:e,children:t=>NT("div",{className:t.className,children:NT(Cig,{title:c.title,oK:d,description:c.subtitle,backgroundColor:g,U1d:k,V1d:l,fi:m,Uv:q,size:b?"responsive":"full"})})})})})}},Gig=function({alt:a,sources:b,src:c,textColor:d,backgroundColor:e,cQa:f,cfb:g,Xmc:k,sne:l,dj:m,s4:q,ST:t,DXc:v}){f=f==="parallax"?Eig:Fig;return PT("div",
{className:QT("MtOiNg",{_37a8Ow:q}),children:[(b.length>0||c!=null)&&NT(f,{alt:a,backgroundColor:e,cfb:g,sources:b,src:c,Xmc:k}),NT("div",{className:"kycOpw",children:PT("div",{className:"XEuxQg",children:[l&&NT("div",{className:"_38me4w",children:NT(l,{})}),m&&NT("div",{className:"bjHglQ",style:{color:d},children:NT(m,{})}),q&&NT("div",{className:"WRuJJQ",children:q}),t&&NT("div",{className:QT("oo_zNQ",{aO2l0Q:v}),style:{color:d},children:NT(t,{})}),v&&NT("div",{className:"DoA9Vg",style:{color:d},
children:NT(v,{})})]})})]})},Fig=function({alt:a,backgroundColor:b,cfb:c=!0,sources:d,src:e}){a=d.length===0&&e==null?null:NT(__c.Dd,{sources:d,sizes:[],src:e,className:"twkIfA",alt:a,draggable:!1});return NT("div",{className:QT("f9h1VQ",c&&"UYECaw"),style:{backgroundColor:b},children:a})},Hig=function(a,b){const c=/(auto|scroll)/;for(;a=a.parentElement;){const d=b.getComputedStyle(a);if(d.position!=="static"&&c.test(`${d.overflow}${d.overflowY}${d.overflowX}`))return[a,a]}return[b,b.document.documentElement]},
Jig=function({C:a,s4:b,Link:c}){const d=__c.KE(new __c.LE(e=>{a.error(e,{Ja:"HtmlRenderer: failed to render html"})}),"A",(e,f,g)=>{if("dataset"in e)try{const k=e.dataset?.link;if(k){const l=__c.Dl.deserialize(JSON.parse(atob(k)));return NT("span",{className:"eyGQ6g",children:NT(c,{model:l,children:f})},g)}}catch(k){a.qa(k,{Ja:"Subtitle: failed to parse subtitle link proto"})}return(e=e.getAttribute("href"))?NT(__c.ae,{href:e,className:"eyGQ6g",children:f},g):f});return{f0c:OT(({model:e})=>{var f=
e.Lxb;const g=e.TBa,k=e.title,l=e.subtitle;if(g&&g.type!=="SINGLE_IMAGE")throw Error(`backgroundThumbnail type "${g.type}" is not implemented in SearchBanner`);let m;if(f!=null){const q=f.bA,t=f.Fxa;m=()=>NT(c,{model:t,children:NT(Iig,{name:q})})}f=g?.yb.map(q=>({src:q.url,Dw:q.width}));return NT(Ig,{$a:"SEARCH_BANNER_HEADER",children:NT("div",{className:"GmVMpw",children:NT(Gig,{sources:f??[],alt:g?.altText||"",backgroundColor:g?.backgroundColor,cQa:e.cQa===1?"parallax":"static",cfb:!1,dj:k?()=>
NT(Yj,{size:"xlarge",tone:__c.Id,alignment:"center",nb:"legacy",children:k}):void 0,ST:l?()=>NT(K,{tone:__c.Id,alignment:"center",nb:"legacy",children:d.render(l)}):void 0,DXc:m,s4:b})})})})}},Lig=function(a,{action:b,location:c}){const d=Kig[b.type];a=a.G;var e=a.Wg;a:switch(b.type){case "DESIGN_WITH_CATEGORY":b=new Map([["requiresAuth",b.Qu],["category",b.category],["doctype",b.doctype]]);break a;case "LINK":b=new Map([["requiresAuth",b.link.Qu],["path",b.link.path],["deepLink",b.link.iid]]);break a;
default:throw new __c.n(b);}e.call(a,d,{Vl:{name:d,type:c,attrs:b}}).end()},Nig=function({Pq:a}){return{k2c:OT(({model:b})=>{let c;if(b.background&&__c.Ebf(b.background)!=null)c=()=>NT(__c.lJ,{play:"always",model:b.background,fit:{direction:"height"},altText:b.background.altText});else if(b.background?.backgroundColor){const d=qig(Ye(b.background.backgroundColor));c=()=>NT("div",{className:"qol0og",style:{backgroundColor:d}})}return NT(Ig,{$a:"VERTICAL_BANNER_HEADER",children:NT(Mig,{title:b.title,
subtitle:b.subtitle,yQ:b.yQ?.Vs,mVc:()=>NT(__c.lJ,{play:"always",model:b.foreground,fit:{direction:"width",aspectRatio:__c.Ebf(b.foreground)},altText:b.foreground.altText}),nsb:c,Gpa:b.fi?()=>NT(a,{action:b.fi,stretch:!0,align:"center",variant:"primary"}):void 0,YOa:b.Uv?()=>NT(a,{action:b.Uv,stretch:!0,align:"center",variant:"secondary"}):void 0})})})}},Oig=__webpack_require__(296713),uig=Oig.Fragment,NT=Oig.jsx,PT=Oig.jsxs;var RT=__webpack_require__(978109),Pig=RT.Component,Qig=RT.createRef,OT=RT.memo,Rig=RT.useCallback,Sig=RT.useEffect,Tig=RT.useMemo,Uig=RT.useRef,Vig=RT.useState;var Wig=__webpack_require__,Xig=Wig(208463),QT=Wig.n_x(Xig)();var Yig=__webpack_require__(245307).Fm;var Zig=__webpack_require__(549056)._;var $ig=__webpack_require__(186901),ajg=$ig.EW,bjg=$ig.sH,cjg=$ig.XI;var djg=__webpack_require__(621369)._;var ejg=__webpack_require__(270531).PA;var fjg=(a,b)=>{const c=d=>{switch(d?.type){case "DESIGN_WITH_CATEGORY":case "LINK":return()=>Lig(b,{action:d,location:"banner"})}};return d=>{const e=d.variant==="primary"?c(d.action):void 0;return e?NT(a,{...d,onClick:()=>{e();d.onClick?.()}}):NT(a,{...d})}};var rig=({title:a,subtitle:b,yQ:c,s4:d})=>PT(yd,{display:"flex",flexDirection:"column",alignItems:"center",paddingBottom:{default:"4u",pb:"6u"},paddingTop:{default:"2u",pb:"3u"},ee:"3u",children:[a&&NT(Yj,{tagName:"h1",className:"FRfLvA",alignment:"center",children:a}),d&&NT(yd,{className:"_8VZFvw",paddingTop:"4u",children:d}),b&&NT(yd,{paddingTop:"3u",children:NT(K,{className:"T0qd9w",alignment:"center",children:b})}),c&&NT(yd,{paddingTop:"3u",children:NT(__c.pN,{className:"T0qd9w",alignment:"center",
Q9:c})})]});var gjg=OT(a=>{const b=a.title,c=a.subtitle;a=a.yQ;return PT("div",{className:"qxiqNA",children:[b&&NT(Yj,{size:"large",tagName:"h1",tone:"primary",nb:"legacy",tabIndex:-1,children:NT("span",{className:"l7B_rg",children:b})}),(c||a)&&PT(__c.jd,{spacing:"1u",children:[c&&NT("div",{className:"_4HbGtg",children:NT(K,{size:"large",children:c})}),a&&NT("div",{className:"_4Ly8Yw",children:NT(__c.pN,{Q9:a,size:"large"})})]})]})});var vig=({title:a,Pib:b,subtitle:c,yQ:d,Ghd:e,button:f,$Vb:g,Db:k,Qqa:l})=>{const m=Uig(null),[q,t]=Vig(void 0),v=parseInt("248px",10)||248,y=Rig(()=>{m.current&&t(m.current.clientHeight)},[]),z=Tig(()=>__c.ib(y,200,{leading:!0}),[y]);Sig(()=>{y();window.addEventListener("resize",z);return()=>{window.removeEventListener("resize",z)}},[y,z]);var A=Tig(()=>{const I=k.backgroundColor?Ye(k.backgroundColor):void 0;return(I&&new __c.gf(I.r,I.g,I.b,l??1))?.bNa()},[k.backgroundColor,l]);A=e?.background?{background:e.background}:
{backgroundColor:A};let C;e?.textColor&&(C=e?.textColor===1?"dark":"light");const F=NT("div",{className:"R8TTIA",children:NT(K,{size:"large",children:c})}),G=qe({default:"medium",pb:"large"});return PT("div",{style:A,className:QT("bDfsrA",{AlrNEg:!e?.background}),ref:m,children:[NT(__c.Od,{light:C,dark:C,pn:C,nx:C,children:I=>NT(yd,{className:QT(I.className,"ZZgnjw",{jLjAPQ:!g,rSCk4A:g}),ee:{default:"2u",pb:"4u"},Ah:{default:"2u",pb:"4u"},children:PT(__c.jd,{spacing:{default:"1u",pb:"2u"},children:[PT(Yj,
{size:G,tagName:"h1",tabIndex:-1,children:[NT(Sj,{GL:"small",tagName:"span",children:b??a}),NT(Sj,{cA:"small",tagName:"span",children:a})]}),c&&(g?NT(Sj,{cA:"small",children:F}):F),d&&NT(__c.pN,{Q9:d,size:"large"}),f&&NT("div",{className:"tXXlwQ",children:f})]})})}),NT("div",{className:"RU_CGg",children:g?NT(hjg,{mA:q,minHeight:v,Db:k}):NT(Sj,{cA:"small",children:NT(hjg,{mA:q,minHeight:v,Db:k})})})]})},hjg=({mA:a,minHeight:b,Db:c})=>NT("div",{className:"gQphnA",children:NT("div",{className:"O_H82Q",
children:NT(__c.lJ,{play:"always",REa:__c.Ph.direction===2,fit:{direction:"height",value:a||b},maxHeight:a??b,model:c,background:"none"})})});var zig=OT(({dj:a,ST:b,Ytb:c,p0c:d,s4c:e})=>PT("div",{className:QT("_361frw",e==="end"&&"_0gF86A"),children:[a&&NT(a,{}),b&&NT("div",{className:"NaNPcA",children:NT(b,{})}),(c||d)&&PT("div",{className:"AH5nfA",children:[c&&NT(c,{}),d&&NT(d,{})]})]}));var Aig=({VQc:a,backgroundColor:b,p1c:c,oK:d})=>PT("div",{className:QT("_1HF8ZA",d&&"A4JOiA"),children:[NT("div",{className:QT("JfiwIQ",!a&&"Hr0Ygg"),style:{backgroundColor:b},children:a}),NT("div",{className:"x5cWgg",children:NT(c,{})})]}),yig=a=>a.map(b=>({src:b.url,Dw:b.width})),xig=a=>a.map(b=>({nl:b.nl===1?1:0,images:yig(b.yb)}));var Cig=OT(({title:a,oK:b,description:c,backgroundColor:d,U1d:e,V1d:f,fi:g,Uv:k,size:l="full"})=>{a=NT(yd,{paddingTop:{default:"2u",Mc:"0"},className:"_6QnooQ",children:NT(yd,{padding:{default:"2u",pb:"4u"},className:"lOUDQw",children:PT(__c.jd,{spacing:{default:"2u",pb:"3u"},children:[a&&NT(Yj,{size:"xlarge",alignment:"inherit",tagName:b?"h2":"h1",children:a}),c&&NT(K,{size:"large",alignment:"inherit",children:c}),(g||k)&&PT(__c.dd,{GX:"small",align:{default:"center",pb:"start"},spacing:{default:"0.5u",
pb:"1u"},children:[g,k]})]})})});return PT("div",{className:QT("k63aLw",{_3BQESQ:l==="full",UhmxAQ:l==="responsive"}),children:[PT(Sj,{cA:"small",children:[NT("div",{className:"d_14_g",style:{backgroundColor:d}}),NT("div",{className:"YNQpvQ",children:f})]}),NT(Sj,{GL:"small",children:NT("div",{className:"YNQpvQ",children:e})}),a]})});var Iig=OT(({name:a})=>{a=__c.GD(a);a=__c.H("DRhz9w",["B8gQeQ",a]);return NT(K,{size:"small",tone:__c.Id,alignment:"center",nb:"legacy",children:NT(__c.wG,{message:a})})});var ijg,jjg,kjg,Eig;
new (ijg=class extends Zig{constructor(){super(Eig);jjg()}},(()=>{class a extends(kjg=Pig){static F(b){__c.vb(b,{dQb:bjg.ref,c9b:cjg.bound,cpc:ajg,image:ajg})}componentDidMount(){const {Xmc:b=Hig}=this.props;__c.Ph.Pb&&this.containerRef.current!=null&&([this.rLa,this.rnb]=b(this.containerRef.current,window),this.rLa!=null&&(this.snb=()=>this.Fwd(),this.rLa.addEventListener("scroll",this.snb),this.snb()))}componentWillUnmount(){this.rLa!=null&&this.rLa.removeEventListener("scroll",this.snb)}c9b(){this.Mwb=
!1;if(this.containerRef.current!=null&&this.rnb!=null){var b=this.rnb.clientHeight,c=this.containerRef.current.getBoundingClientRect();this.dQb=1-Math.min(Math.max(b-c.top,0)/(b+c.height),1)}}get cpc(){return`translateY(calc(${"30vh"} * -${this.dQb}))`}get image(){const b=this.props.sources,c=this.props.src;return b.length===0&&c==null?null:NT(__c.Dd,{sources:b,sizes:[],src:c,className:"KAQO2w",style:{transform:this.cpc},alt:this.props.alt,draggable:!1})}render(){const {backgroundColor:b,cfb:c=!0}=
this.props;return NT("div",{ref:this.containerRef,className:QT("f9h1VQ",c&&"UYECaw"),style:{backgroundColor:b},children:this.image})}constructor(...b){super(...b);this.containerRef=(Eig.F(this),Qig());this.Mwb=!1;this.rnb=this.rLa=void 0;this.dQb=.5;this.snb=void 0;this.Fwd=()=>{var c=window;const d=this.rLa,e=this.rnb,f=this.image;this.Mwb||d==null||e==null||f==null||(this.Mwb=!0,c.requestAnimationFrame(Yig.wrap(this.c9b)))}}}({c:[Eig,jjg]}=djg(a,[],[__c.Lb],kjg))})(),ijg);var Kig={DESIGN_WITH_CATEGORY:"marketplace.click_design_with_category_action",LINK:"marketplace.click_link_action"},ljg=class{constructor(a){this.G=a.nh("marketplace.server_driven_ui.banner")}};var Mig=OT(a=>{const b=a.title,c=a.subtitle,d=a.yQ,e=a.mVc,f=a.nsb,g=a.Gpa;a=a.YOa;return PT("div",{className:"ExFYwg",children:[f&&NT("div",{className:"_0omLlw",children:NT(f,{})}),PT("div",{className:"Gf8ZKg",children:[b&&NT("div",{className:"kjUbnA",children:NT(Yj,{size:"xlarge",alignment:"center",nb:"legacy",children:b})}),c&&NT(K,{size:"large",alignment:"center",nb:"legacy",children:c}),d&&NT(__c.pN,{size:"large",alignment:"center",nb:"legacy",Q9:d})]}),(g||a)&&PT("div",{className:"nPSA7g",children:[g&&
NT(g,{}),NT("div",{className:"NYvDPA",children:a&&NT(a,{})})]}),NT("div",{className:"yQbVew",children:NT("div",{className:"FcrKQA",children:NT(e,{})})})]})});__c.wdf={LAb:function({C:a,Link:b,s4:c,Pq:d,tda:e,xa:f,Ab:g,session:k,ne:l,NL:m}){l=new ljg(l);l=fjg(d,l);const {f0c:q}=Jig({Link:b,s4:c,C:a.Hf("search_banner")}),{ASc:t}=wig({Pq:d,$Vb:!!k}),{pWc:v}=Dig({Pq:l,tda:e}),{vRc:y}=Big({Pq:d}),{k2c:z}=Nig({Pq:l}),{Dsb:A}=tig(),{cRc:C}=sig({s4:c}),F=ejg(({model:G,oK:I,expand:L})=>{const O=__c.Kg(),P=Rig(()=>{f.Ou(O)},[O]);if(qe({default:G.TFa,pb:!1}))return null;let R;switch(G.type){case "SEARCH_BANNER":R=NT(q,{model:G});break;case "COMPACT_LABEL":R=NT(gjg,
{title:G.title,subtitle:G.subtitle,yQ:G.yQ?.Vs});break;case "CONTEXTUAL_BANNER":R=NT(t,{model:G});break;case "CTA_BANNER":R=NT(y,{model:G,oK:I});break;case "VERTICAL_BANNER":R=NT(z,{model:G});break;case "HORIZONTAL_BANNER":R=NT(v,{model:G,oK:I});break;case "COLLECTION_BANNER":R=NT(A,{model:G});break;case "BORDERLESS_BANNER":R=NT(C,{model:G});break;default:throw new __c.n(G);}return NT(__c.il,{Ab:g,Cp:U=>U&&P(),Ds:!0,children:({ref:U})=>NT("div",{ref:U,className:QT(I&&"wI__cg",L&&"_2EU65g"),children:R})})});
return ejg(({model:G})=>{const I=!(G.uh.type==="COLLECTION_BANNER"||G.uh.type==="CONTEXTUAL_BANNER"),L=m.get();return PT(uig,{children:[NT(F,{model:G.uh,oK:G.uh.oK??G.oK,expand:I}),L&&PT(uig,{children:[NT(__c.Ie,{size:{default:"2u",Mc:"4u"}}),L]})]})})}};
}).call(globalThis, globalThis._456c437108d2d2713799e19380be528d);}

}])
//# sourceMappingURL=sourcemaps/7c4bc21bc568c9a4.js.map