(globalThis["webpackChunk_canva_web"] = globalThis["webpackChunk_canva_web"] || []).push([[95773],{

/***/ 658999:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);__web_req__(93415);globalThis._456c437108d2d2713799e19380be528d = globalThis._456c437108d2d2713799e19380be528d || {};(function(__c) {var Wc=__c.Wc;var Tc=__c.Tc;var AC=__c.AC;var PC;var nd=__c.nd;var J=__c.J;var lqc,nqc,oqc,uqc,qqc,zqc,Bqc,Cqc,Dqc,Hqc,pqc,Jqc,Kqc,Mqc,Nqc,IC,KC;__c.iqc=function(a,b){a.observer?.disconnect();a.observer=new IntersectionObserver(a.g9d,{threshold:.7,...b});a.init()};__c.jqc=function(a,b){return a.rg.Jo(__c.vAa(b))};
lqc=function({orientation:a,size:b="medium",className:c,style:d}){b=kqc[b];a=a==="left"?"translate(24 0) scale(-1 1)":void 0;return IC("span",{className:JC("cb_YGw",c),style:d,children:IC("svg",{width:b,height:b,viewBox:"0 0 24 24","aria-hidden":"true",focusable:"false",className:"N00prg",children:KC("g",{transform:a,children:[IC("path",{d:"m9.216 7.619 4.204 4.204a.25.25 0 0 1 0 .354l-4.204 4.204a.75.75 0 0 0 1.06 1.061l4.205-4.204a1.75 1.75 0 0 0 0-2.475l-4.204-4.205a.75.75 0 0 0-1.061 1.06",className:"iBQU9w",
strokeLinecap:"round",strokeLinejoin:"round"}),IC("path",{d:"m9.216 7.619 4.204 4.204a.25.25 0 0 1 0 .354l-4.204 4.204a.75.75 0 0 0 1.06 1.061l4.205-4.204a1.75 1.75 0 0 0 0-2.475l-4.204-4.205a.75.75 0 0 0-1.061 1.06",className:"_TbWJw"})]})})})};nqc=function(a,b){const c=mqc();b=b==="forward"?J("YUXvxQ"):J("IDhDQA");return a.zb!=null?{zb:`${c} ${a.zb}`,noc:IC(__c.Ld,{id:c,mxb:!0,tagName:"span",children:`${b}:`})}:a.ariaLabel!=null?{ariaLabel:`${b}: ${a.ariaLabel}`}:{ariaLabel:b}};
oqc=function(a,b,c,d){if(b!=="bounded"||c==null&&d==null)return a;d=(b=d&&(d.direction==="backward"?1:-1))&&d.offsetX*b;return IC("div",{style:{"--VJZgsQ":d?`${d}px`:void 0,"--Wxzfbw":c?`${c}px`:void 0},children:a})};
uqc=function(a){const {onScroll:b,UV:c,tR:d=0,gap:e=0,vIb:f,u2e:g,Xn:k}=a,l=LC(null),m=LC(null),q=LC(void 0),t=LC(null),v=MC(L=>{if(f!=null)return typeof f==="number"?f:f(L);L=t.current?.children.item(L);return L!=null?L instanceof(L.ownerDocument?.defaultView??window).HTMLElement?L.offsetWidth:L.clientWidth:0},[t,f]),y=MC(L=>{if(g!=null)return typeof g==="number"?g:g(L);L=t.current?.children.item(L);return L!=null?L instanceof(L.ownerDocument?.defaultView??window).HTMLElement?L.offsetHeight:L.clientHeight:
0},[t,g]),z=MC((L,O)=>{L=k??L.children.length;l.current=O.YWb?pqc({umc:v,Xn:L,gap:e}):null;m.current=O.$Ec?pqc({umc:y,Xn:L,gap:e}):null;O=qqc({ZEc:O,Rrc:l.current,Src:m.current});c?.(O);q.current=O},[e,y,v,c,k]);a=MC(L=>{L=qqc({ZEc:L,Rrc:l.current,Src:m.current});b?.(L)},[b]);const A=MC(L=>{t.current!=null&&t.current.offsetParent!=null&&z(t.current,L)},[z]),{handle:C,ref:F,onScroll:G}=__c.Tpc({onScroll:a,UV:A,tR:d}),I=rqc(()=>({...C,I7:()=>q.current,Jya:L=>{C.scrollBy({...L,x:L.x!=null&&q.current?.Tk!=
null&&q.current?.Nva?.M0!=null&&l.current!=null?sqc({Vzc:L.x,M0:q.current?.Nva?.M0,qO:q.current?.Tk,UG:l.current,Rv:q.current?.x}):void 0,y:L.y!=null&&q.current?.mA!=null&&q.current?.XGa?.M0!=null&&m.current!=null?sqc({Vzc:L.y,M0:q.current?.XGa?.M0,qO:q.current?.mA,UG:m.current,Rv:q.current?.y}):void 0})},IZ:L=>{C.scrollTo({...L,x:L.x!=null&&l.current!=null&&q.current?.Tk!=null?tqc({yda:L.x,qO:q.current?.Tk,Rv:q.current?.x,xda:L.xda,UG:l.current}):void 0,y:L.y!=null&&m.current!=null&&q.current?.mA!=
null?tqc({yda:L.y,qO:q.current?.mA,Rv:q.current?.y,xda:L.xda,UG:m.current}):void 0})},qnb:L=>{const {xda:O="start"}=L;I.IZ({x:L.x!=null&&q.current?.Nva!=null?Math.min(Math.max(0,q.current.Nva.M0[O]+L.x),q.current.Nva.numberOfItems-1):void 0,y:L.y!=null&&q.current?.XGa!=null?Math.min(Math.max(0,q.current.XGa.M0[O]+L.y),q.current.XGa.numberOfItems-1):void 0,xda:O})}}),[C]);a=MC(L=>{t.current=L},[]);return{ref:nd(a,F),handle:I,onScroll:G}};
qqc=function({ZEc:a,Rrc:b,Src:c}){return{...a,Nva:b!=null?vqc({UG:b,Rv:a.x,qO:a.Tk}):null,XGa:c!=null?vqc({UG:c,Rv:a.y,qO:a.mA}):null}};zqc=function({Cp:a}){const {observer:b,callbacks:c}=wqc(xqc),d=yqc(e=>{a?.(e)});return{ref:MC(e=>{c?.set(e,d);b?.observe(e);return()=>{c?.delete(e);b?.unobserve?.(e)}},[b,c])}};
Bqc=function({children:a,disable:b}){const [c,d]=NC(void 0),[e,f]=NC(void 0),g=MC(l=>{const m=new WeakMap,q=new IntersectionObserver(t=>{t.forEach(v=>{v.intersectionRatio>=.7?m?.get(v.target)?.(!0):v.rootBounds?v.boundingClientRect.width>v.rootBounds.width?m?.get(v.target)?.(v.intersectionRatio>=.1):m?.get(v.target)?.(!1):m?.get(v.target)?.(!1)})},{root:l,threshold:[0,.1,.5,.7,1]});f(m);d(q);return()=>{q.disconnect()}},[]),k=rqc(()=>({observer:c,callbacks:e}),[c,e]);return b?a({ref:Aqc}):IC(xqc.Provider,
{value:k,children:a({ref:g})})};Cqc=function(a,b){var c={once:!0};if(a&&b){var {once:d,tR:e=50}=c,f=__c.ib(()=>{b();d&&a.removeEventListener("scroll",f)},e);a.addEventListener("scroll",f)}};
Dqc=function(){const a=LC(null),b=LC(null),c=yqc(f=>{for(f=f.target;f?.parentElement!=null&&f.parentElement!==a.current;)f=f.parentElement;b.current=f}),d=yqc(()=>{if(!b.current||b.current.inert){var f=a.current;if(f!=null){var g=null;for(let k=0;k<f.children.length-1;k++){const l=f.children.item(k);if(l?.getAttribute("inert")==null){g=l;break}}g&&__c.Qi(g)?.focus({preventScroll:!0})}}else __c.Qi(b.current)?.focus({preventScroll:!0})}),e=yqc(()=>{if(!b.current||b.current.inert){var f=a.current;if(f!=
null){var g=null;for(let k=f.children.length-1;k>0;k--){const l=f.children.item(k);if(l?.getAttribute("inert")==null){g=l;break}}g&&__c.Qi(g)?.focus({preventScroll:!0})}}else __c.Qi(b.current)?.focus({preventScroll:!0})});return{ref:a,onFocus:c,ltd:d,rtd:e}};
__c.Eqc=function(a){const b=IC(__c.Yc,{x:a.Kfa?"0":"2u",children:KC(__c.OC,{ariaLabel:J("HGw+nQ"),gap:"1u",Qr:"0",ee:a.Kfa?"0":"2u",Fz:()=>null,children:[a.Hza&&IC(PC,{children:a.Hza}),a.JGb&&IC(PC,{children:IC("div",{className:"_5s8Tvw",children:a.JGb})}),a.IGb&&IC(PC,{children:IC("div",{className:"il6_JA",children:a.IGb})}),a.vfa&&IC(PC,{children:a.vfa})]})});return IC(__c.Ig,{$a:"NAVIGATION_FLYOUT",children:KC(__c.yd,{display:"flex",flexDirection:{default:"column",Mc:"row"},children:[a.Kfa&&IC(__c.yd,
{className:"akYfNA",flex:"none",children:a.Kfa}),a.Kfa&&IC(__c.Ie,{size:"1.5u"}),IC(__c.yd,{role:"group",ariaLabel:J("HGw+nQ"),minWidth:"0",children:b})]})})};__c.Gqc=function({dF:a,QAa:b,Kfa:c}){return{e6b:Fqc(({Xs:d,Zwd:e,Hza:f})=>{d=d?.tags.length?IC(b,{Xs:d,Joa:!1}):void 0;const g=e&&a?IC(a.U6a,{}):void 0;e=e&&a?IC(a.eha,{}):void 0;return IC(__c.Eqc,{JGb:g,IGb:e,vfa:d,Hza:f,Kfa:c})})}};
__c.Iqc=function({Link:a,xa:b,Ab:c}){const d=({children:g,href:k,onClick:l})=>IC(__c.Vd,{variant:"secondary",href:k,onClick:l,children:g}),e=({tag:g})=>IC(a,{model:g.link,Mn:d,children:IC(__c.K,{tone:__c.Id,children:g.text})}),f=({vfa:g,Joa:k})=>{const l=__c.Kg(),m=MC(()=>{const q=Hqc(g);b.Ou(l,{Yn:q});l.component?.$a&&b.H9({rows:[{bd:l.component,type:l.component.$a,Qm:l.component.Qm,bda:0}]})},[l,g]);return IC(__c.il,{Ab:c,Cp:q=>q&&m(),Ds:!0,children:({ref:q})=>IC("div",{ref:q,children:k?IC(__c.OC,
{gap:"1u",ariaLabel:void 0,Qr:"0",children:g.map(t=>IC(PC,{children:IC(e,{tag:t})},t.text))}):IC(__c.bd,{Wc:"start",spacing:"1u",children:g.map(t=>IC(__c.Zc,{width:"content",children:IC(e,{tag:t})},t.text))})})})};return{hub:({Xs:g,Joa:k})=>IC(__c.Ig,{$a:g.Qaa,children:IC(f,{vfa:g.tags,Joa:k})})}};Hqc=function(a){return a.map(b=>b.link.uG?.type==="CATEGORY"?b.link.uG.Ea:void 0).filter(__c.jb)};__c.Oi.prototype.ueb=__c.ca(79,function(a,b){return this.rg.Jo(new __c.zi({path:__c.yi("DREAM_LAB",{}),target:__c.ti(b?.target)}))});
pqc=({Xn:a,umc:b,gap:c=0})=>{const d=[],e=[],f=[],g=[];let k=0;Array.from({length:a},()=>{}).forEach((l,m)=>{m!==0&&(k+=c);d.push(k);l=b(m);g.push(l);e.push(k+l/2);k+=l;f.push(k);return k});return{lYa:f,CDd:e,MMb:d,itemSizes:g,d7d:k}};Jqc=["aJFp1g AdcdQg","VtWaFQ AdcdQg","_jSw2Q AdcdQg","u49jNQ AdcdQg"];Kqc=[2E3,3E3,4E3,2E3];
__c.Lqc=a=>{const {value:b,ariaLabel:c,size:d="medium",tone:e="info",kg:f,Cea:g,Rgc:k}=a,[l,m]=(0,__c.bqc)([]),q=__c.fb(),t=(0,__c.Qpc)({myb:0,JBb:!1,sRb:0,width:0}),v=(0,__c.CC)(()=>{const A=Date.now(),C=t.current.width/100*b;var F=Math.ceil(C*.13);const G=F-l.length;let I=!1;F=Array.from({length:G<0?F:Math.ceil(l.length+G/2)},(L,O)=>{L=l[O];return L===void 0||A>Kqc[L.type]+L.start?(I=!0,{aLc:L?!L.aLc:!1,type:Math.floor(Math.random()*Jqc.length),position:Math.floor(Math.random()*C),start:A}):L});
I&&m(F);window.clearTimeout(t.current.myb);t.current.myb=window.setTimeout(__c.cqc.wrap(v),1E3)},[l,b]),y=(0,__c.CC)(()=>{window.clearTimeout(t.current.sRb);t.current.JBb||(t.current.JBb=!0,g&&g(b))},[g,b]);(0,__c.Rpc)(()=>{const A=t.current.myb;return()=>{window.clearTimeout(A)}},[]);(0,__c.Rpc)(()=>{q&&!k&&v();__c.na(b>=0&&b<=100,`value must be in [0, 100]; got ${b}`);t.current.JBb=!1;window.clearTimeout(t.current.sRb);t.current.sRb=window.setTimeout(__c.cqc.wrap(y),__c.eqc)},[b,k,y,v,q]);const z=
{transform:`scaleX(${b/100})`};return AC(__c.dqc,{onResize:A=>{A.entry&&(t.current.width=A.entry.width)},children:({measureRef:A})=>AC("div",{ref:A,className:(0,__c.EC)("WOKrpg",{w29trQ:d==="small",BwUf7g:e==="critical",aBvcYQ:!f&&q}),role:"progressbar","aria-label":c,"aria-valuemin":0,"aria-valuenow":b,"aria-valuemax":100,children:AC("div",{className:"LaSi3g mPCClQ",style:{"--qaorvg":`${b-100}%`},children:(0,__c.DC)("div",{className:"LaSi3g mPCClQ",style:{"--qaorvg":`${100-b}%`},children:[AC("div",
{className:"QgOdhA mPCClQ",style:z,onTransitionEnd:y}),l.map(({position:C,type:F,aLc:G},I)=>AC("div",{className:(0,__c.EC)(Jqc[F],{mYGiIA:G}),style:{"--2b1ctA":`${C}px`}},I))]})})})})};Mqc=__webpack_require__(296713);Nqc=Mqc.Fragment;IC=Mqc.jsx;KC=Mqc.jsxs;var Oqc=__webpack_require__,Pqc=Oqc(208463),JC=Oqc.n_x(Pqc)();var QC=__webpack_require__(978109),Qqc=QC.Children,Rqc=QC.createContext,RC=QC.memo,MC=QC.useCallback,wqc=QC.useContext,Sqc=QC.useEffect,yqc=QC.useEffectEvent,mqc=QC.useId,Tqc=QC.useImperativeHandle,rqc=QC.useMemo,LC=QC.useRef,NC=QC.useState;var Fqc=__webpack_require__(270531).PA;var kqc={Ys:12,small:16,medium:24,yh:32},Uqc=a=>IC(lqc,{...a,orientation:"right"}),Vqc=a=>IC(lqc,{...a,orientation:"left"});var Wqc=a=>{const b=nqc({ariaLabel:a.ariaLabel,zb:a.zb},a.direction);var c=__c.Bd();const d=a.dO===!0&&a.direction==="backward"||a.cO===!0&&a.direction==="forward",e=a.position==="detached"||!d;c=JC("ywraoA",{qQtUQw:a.position==="bounded",z9mEkw:a.direction==="forward",hRIG1Q:a.direction==="backward",qt07XQ:c});const f=MC(k=>{a.b6&&(a.b6.current=k)},[a.b6]),g=MC(()=>{a.b6&&(a.b6.current=null)},[a.b6]);Sqc(()=>{e||g()},[g,e]);return{B9b:b,onClick:a.onClick,XIc:e,isDisabled:d,className:c,b6:f}},Xqc=
({position:a="bounded",size:b="medium",offsetY:c,offsetX:d,...e})=>{const {B9b:f,className:g,onClick:k,b6:l,XIc:m,isDisabled:q}=Wqc({...e,position:a});if(!m)return null;const t=f.ariaLabel!=null?{ariaLabel:f.ariaLabel}:{zb:f.zb};return KC(Nqc,{children:[f.noc,oqc(IC(__c.Zd,{variant:"secondary",size:b,LDb:!0,icon:e.direction==="forward"?__c.gg:__c.Gh,Uf:e.xnb,onClick:k,Sg:JC(g,"dFvt1A"),ref:l,disabled:q,...t}),a,c,d?{offsetX:d,direction:e.direction}:void 0)]})},Yqc=({position:a="bounded",...b})=>{const {B9b:c,
className:d,onClick:e,b6:f,XIc:g,isDisabled:k}=Wqc({...b,position:a});if(!g)return null;const l=b.direction==="forward"?Uqc:Vqc;return KC(Nqc,{children:[c.noc,oqc(IC(__c.qg,{type:"button",className:JC(d,"Cucysg",{_0QToGw:k}),onClick:e,Uf:b.xnb,ariaLabel:c.ariaLabel,zb:c.zb,ref:f,disabled:k,children:IC(l,{size:"medium",className:"rK1WOA"})}),a,b.offsetY)]})};var Zqc=({UG:a,Rv:b,qO:c})=>{const d=b+c/2;c=b+c;const e=a.itemSizes.length;let f=-1,g=-1,k=-1,l=Infinity,m=!1;for(let t=0;t<e;t++){var q=a.MMb[t];const v=a.lYa[t];if(f===-1&&(q>b||Math.abs(q-b)<=1))if(q>c){f=t-1;g=t-1;k=t-1;break}else if(v<c||Math.abs(v-c)<=1)f=t;else{k=g=f=t;break}m||(q=Math.abs(d-a.CDd[t]),q<l?(l=q,g=t):m=!0);if(m)if(v<c||Math.abs(v-c)<=1)k=t;else break}return{start:f===-1?g:f,center:g,end:k===-1?g:k}},vqc=({UG:a,Rv:b,qO:c})=>({M0:Zqc({UG:a,Rv:b,qO:c}),numberOfItems:a.lYa.length}),
tqc=({yda:a,qO:b,Rv:c,UG:d,xda:e="start"})=>{const f=d.MMb[a],g=d.lYa[a];return e==="nearest"?(e=g>c+b,f<c||e?tqc({yda:a,qO:b,Rv:c,UG:d,xda:e?"end":"start"}):c):e==="start"?f:e==="end"?Math.max(0,d.lYa[a]-b):Math.max(0,f-b/2+d.itemSizes[a]/2)},sqc=({Vzc:a,M0:b,qO:c,UG:d,Rv:e})=>{const f=b.start;b=b.end;const g=d.MMb,k=d.lYa;d=d.d7d;return a===1?b===g.length-1?Math.min(c,d-c-e):g[b+1]-g[f]:a===-1?f===0?Math.max(-c,-e):k[f-1]-k[b]:c*a};var xqc=Rqc({observer:void 0,callbacks:void 0}),Aqc=()=>{};var $qc=Rqc({hMa:"start",plc:()=>{}}),irc=({direction:a,Qr:b="6u",gap:c="2u",children:d,id:e,J4:f="proximity",hMa:g="start",padding:k,ee:l,Ah:m,paddingTop:q,paddingBottom:t,Hv:v,Gv:y,ref:z,zl:A,onScroll:C,UV:F,sK:G="intrinsic",Jzc:I="inert",role:L,ariaLabel:O,zb:P,md:R,ariaSetSize:U,vIb:W,Xn:Z,onFocus:Y})=>{const [S,ia]=NC(!0),[ja,ka]=NC(!0),[da,la]=NC(0),ta=__c.hb(),pa=a==="horizontal";a=!pa;const Ca=MC(Ya=>{F?.(Ya);pa?(U==null&&la(Ya.Nva?.numberOfItems||0),ia(Ya.dO),ka(Ya.cO)):(U==null&&la(Ya.XGa?.numberOfItems||
0),ia(Ya.sxb),ka(Ya.pxb))},[F,pa,U]),xa=__c.qe(typeof c==="object"?c:{default:c}),ya=parseFloat(xa)*__c.Pd,{ref:sa,handle:va,onScroll:Da}=uqc({onScroll:C,UV:Ca,gap:ya,vIb:W,Xn:Z});Tqc(z,()=>arc(va,g==="none"?"start":g,ta==="RTL"));const {className:La,style:Pa}=__c.iha({display:"flex",flexDirection:pa?"row":"column",flexWrap:"noWrap",columnGap:pa?c:void 0,rowGap:a?c:void 0});c=__c.qe(typeof G==="object"?G:{default:G});const bb=c!=="intrinsic"?Math.floor(100/parseFloat(c)):1,Wa=JC("XmRDGw C3qtwA iC_woA",
La,[(k||l||m||q||t||v||y)&&"Me3ejg"],{qwEVbg:pa,_0dfZ_w:a,scsavA:b!=="0"&&!S,eJiAVQ:b!=="0"&&!ja,_4L8cig:f==="mandatory",Jvb7NA:f==="proximity",Xf5xeQ:b==="3u",_2cz4Pw:b==="6u",taNfXA:b==="12u"}),pb=LC(null),gb=MC(()=>{pb.current?.focus({preventScroll:!0})},[]);b=rqc(()=>({hMa:g,sK:G,role:L,plc:gb,numberOfItems:U??da}),[g,G,L,gb,da,U]);return IC($qc.Provider,{value:b,children:IC(Bqc,{disable:I==="none",children:({ref:Ya})=>{Ya=nd(sa,pb,A,Ya);var Sa={...(k&&Tc(brc,k,Wc)),...(l&&Tc(crc,l,Wc)),...(m&&
Tc(drc,m,Wc)),...(q&&Tc(erc,q,Wc)),...(t&&Tc(frc,t,Wc)),...(v&&Tc(grc,v,Wc)),...(y&&Tc(hrc,y,Wc))};return IC("div",{id:e,ref:Ya,onScroll:Da,className:Wa,style:{...Pa,...Sa,"--rlSUnQ":`${ya}px`,"--sk9ikg":bb},role:L,"aria-label":P?void 0:O,"aria-labelledby":P,"aria-describedby":R,onFocus:Y,children:d})}})})},arc=(a,b,c)=>({I7:()=>a.I7(),scrollTo:d=>a.scrollTo({rtl:c,...d}),scrollBy:d=>a.scrollBy({rtl:c,...d}),tnb:d=>a.tnb({rtl:c,...d}),Jya:d=>a.Jya({...d}),IZ:d=>a.IZ({xda:b,rtl:c,...d}),qnb:d=>a.qnb({rtl:c,
xda:b,...d})}),brc={default:"--n-rkYA",pb:"--OhIXHw",Mc:"--6h1yBw",Ug:"--QPFCnQ",Wj:"--8lJd3A"},crc={default:"--aOKitg",pb:"--Ulaa4Q",Mc:"--6GoYpg",Ug:"--qnJjSA",Wj:"--B3LcPA"},drc={default:"--_2G9Zg",pb:"--bJW57A",Mc:"--8xtt1Q",Ug:"--g-Q1Og",Wj:"--phxUqA"},erc={default:"--X4o5IQ",pb:"--TmuOPA",Mc:"--XPIGyA",Ug:"--LNX7Dg",Wj:"--PAuvBw"},frc={default:"--ud1SSQ",pb:"--PonzLA",Mc:"--Z4m2FQ",Ug:"--lZcP0A",Wj:"--SScMJQ"},grc={default:"--1LTx6w",pb:"--aW1Exg",Mc:"--o7VykQ",Ug:"--3804cA",Wj:"--F_cbMA"},
hrc={default:"--rucCGA",pb:"--vopvBQ",Mc:"--ibSRpg",Ug:"--fTJBTw",Wj:"--1N1XHg"},jrc={default:"--xqmAqA",pb:"--O2OO4w",Mc:"--fszzkg",Ug:"--cbI4Pw",Wj:"--DMP83A"},krc=a=>a!=="intrinsic"?Tc(jrc,a,b=>b==="intrinsic"?"auto":b):void 0,lrc=RC(function({children:a,hMa:b,size:c,role:d,index:e}){const {hMa:f,role:g,sK:k,plc:l,numberOfItems:m}=wqc($qc);b=b||f;c=c||k||"intrinsic";d=d||(g==="list"?"listitem":void 0);const [q,t]=NC(!1),v=LC(null);b=JC("zAWjSA GLyNIw",{zC5NZw:b==="center",LCD1cA:b==="end",dnZWVQ:b===
"none"},c!=="intrinsic"?"p9PpRg":void 0);c=krc(c);const {ref:y}=zqc({Cp:z=>{t(!z);const A=v.current;A&&!z&&(A===document.activeElement||A.contains(document.activeElement))&&l()}});return IC("div",{role:d,className:b,style:c,inert:q,ref:nd(v,y),"aria-setsize":d==="listitem"?m:void 0,"aria-posinset":d==="listitem"&&e!=null?e+1:void 0,children:a})});var orc,nrc,rrc,prc,qrc;__c.SC=a=>IC(Xqc,{position:"bounded",...a});__c.mrc=a=>IC(Yqc,{position:"bounded",...a});
__c.OC=RC(function({role:a,ariaLabel:b,zb:c,md:d,ariaSetSize:e,children:f,onScroll:g,UV:k,zl:l,jQ:m,padding:q,ee:t,Ah:v,paddingTop:y,paddingBottom:z,Hv:A,Gv:C,gap:F="2u",J4:G="proximity",hMa:I="start",yL:L,P1d:O,ISa:P=!0,Jzc:R="inert",Qr:U="6u",z$e:W="intrinsic",Fz:Z=Y=>IC(__c.SC,{...Y})}){const Y=LC(null),S=LC(null),ia=mqc();var ja=__c.qe(typeof F==="object"?F:{default:F});const ka=parseFloat(ja)*__c.Pd,da=L?Array.isArray(L.z2)?L.z2:Array(Qqc.count(f)).fill(L.z2):void 0,la=MC(gb=>da?da[gb]:0,[da]),
ta=LC(null);Tqc(m,()=>nrc(ta));const [pa,Ca]=NC(!0),[xa,ya]=NC(!0);m=__c.Jc(gb=>{gb=orc(gb);k?.(gb);Ca(gb.dO);ya(gb.cO)});ja=__c.Jc(gb=>{g?.(orc(gb))});const {ref:sa,onFocus:va,ltd:Da,rtd:La}=Dqc(),Pa={id:ia,onFocus:va,direction:"horizontal",ref:ta,UV:m,onScroll:ja,J4:G,hMa:I,padding:q,ee:t,Ah:v,paddingTop:y,paddingBottom:z,Hv:A,Gv:C,gap:F,Qr:U,role:a,ariaLabel:b,zb:c,md:d,ariaSetSize:e,Jzc:R},bb=MC(()=>{ta.current?.Jya({x:-1})},[ta]),Wa=MC(()=>{ta.current?.Jya({x:1})},[ta]),pb=LC(null);return IC("div",
{className:"jpmDSA",ref:pb,tabIndex:-1,children:KC(prc,{Z9c:b,ISa:P,scrollMarginTop:O,children:[Z({xnb:ia,direction:"backward",onClick:()=>{R==="inert"&&(pb.current?.focus(),Cqc(sa.current,La));bb()},dO:pa,cO:xa,b6:Y,QOd:S,ariaLabel:b,zb:c}),L?IC(__c.joa,{innerRef:l,layout:"horizontal",children:({zl:gb,bs:Ya})=>IC(irc,{zl:nd(gb,sa),vIb:la,Xn:da.length,...Pa,children:IC(qrc,{yL:L,bs:Ya,z2:da,Lrc:ka,children:f,J4:G})})}):IC(irc,{zl:nd(l,sa),sK:W,...Pa,children:f}),Z({xnb:ia,direction:"forward",onClick:()=>
{R==="inert"&&(pb.current?.focus(),Cqc(sa.current,Da));Wa()},dO:pa,cO:xa,b6:S,QOd:Y,ariaLabel:b,zb:c})]})})});orc=a=>{const b=a.Nva,c=a.pageX;return{x:a.x,M0:b?.M0,numberOfItems:b?.numberOfItems,HBb:c?.HBb,WPb:c?.WPb,Sv:a.YWb,Tk:a.Tk,mA:a.mA,scrollWidth:a.scrollWidth,scrollHeight:a.scrollHeight,dO:a.dO,cO:a.cO}};
nrc=a=>{const b=a?.current;return{I7:()=>{const c=b?.I7();return c?orc(c):void 0},scrollTo:(c,d)=>b?.scrollTo({x:c,...d}),scrollBy:(c,d)=>b?.scrollBy({x:c,...d}),tnb:(c,d)=>b?.tnb({x:c,...d}),Jya:(c,d)=>b?.Jya({x:c,...d}),IZ:(c,d)=>b?.IZ({x:c,...d}),qnb:(c,d)=>b?.qnb({x:c,...d})}};PC=__c.PC=({width:a,...b})=>IC(lrc,{...b,size:a});rrc=RC(function({width:a}){return IC("span",{className:"o0qdKw",style:{width:a}})});
prc=RC(function({Z9c:a,children:b,scrollMarginTop:c,ISa:d}){const e=mqc(),f=mqc();return d?b:KC(Nqc,{children:[IC(__c.mDa,{id:e,scrollMarginTop:c,label:a?__c.H("LckcsA",[a]):J("maTNiA")}),IC(__c.Sp,{to:f,position:"top",children:a?__c.H("70xSVA",[a]):J("m8gVcA")}),b,IC(__c.Sp,{to:e,position:"bottom",children:a?__c.H("EtH2Sg",[a]):J("XiRPqg")}),IC(__c.mDa,{id:f,scrollMarginTop:c,label:a?__c.H("RK5cHQ",[a]):J("zBSOaw")})]})});
qrc=RC(function({bs:a,yL:b,z2:c,Lrc:d=0,children:e,J4:f}){const g=rqc(()=>{const k=d>0?c.map(l=>l+d):c;d>0&&k.length>0&&(k[k.length-1]-=d);return k},[d,c]);return IC(__c.Ok,{bs:a,itemSizes:g,Mea:b.Mea,children:(k,l)=>{const {cK:m,vK:q}=k??{cK:0,vK:Math.min(b.F7e??1,l.length-1)};if(f!=="none")return Qqc.map(e,(t,v)=>{const y=Array.isArray(b.z2)?b.z2[v]:b.z2;return m<=v&&v<q?t:IC(PC,{index:v,children:IC(rrc,{width:y})})});k=l[m];k=k===0?0:k-d;l=l[l.length-1]-l[q];return KC(Nqc,{children:[k!==0&&IC(rrc,
{width:k}),Qqc.toArray(e).slice(m,q),l!==0&&IC(rrc,{width:l})]})}})});
}).call(globalThis, globalThis._456c437108d2d2713799e19380be528d);}

}])
//# sourceMappingURL=sourcemaps/82da106b9770e71f.js.map