(globalThis["webpackChunk_canva_web"] = globalThis["webpackChunk_canva_web"] || []).push([[70736],{

/***/ 499464:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);__web_req__(296452);__web_req__(16433);globalThis._456c437108d2d2713799e19380be528d = globalThis._456c437108d2d2713799e19380be528d || {};(function(__c) {var yd=__c.yd;var rF=__c.rF;var qF=__c.qF;var vb=__c.vb;var AO;var zO;var yO;var wO;var $a=__c.$a;var oqf,sqf,tqf,uqf,yqf,vqf,Aqf,CO,Hqf,Iqf,Jqf,Kqf,Nqf,Oqf,Pqf,vO;__c.uO=function(a,b){return a.$Xa(b)?a.HQ===1?__c.ID(a.bg)?0:1:2:3};oqf=function({children:a}){return __c.ad.count(a)<2?a:(0,__c.E)("div",{className:"UfYDHQ",children:__c.ad.map(a,(b,c)=>(0,__c.E)("div",{className:"YVd8lA",children:b},c))})};
__c.pqf=function(a){a:{var b=a.type;switch(b){case "TEMPLATE":b=2;break a;case "ICON":case "PHOTO":b=1;break a;default:throw new __c.n(b);}}return new __c.kh(new __c.kl({type:b,object:a.id,Gm:a.yn}))};
__c.qqf=function({children:a,mg:b=!1,$ua:c=!0,lr:d,MVa:e,threshold:f=250,mJf:g=!1,OOc:k=!0,className:l}){const m=(0,__c.Za)(null),q=(0,__c.db)(()=>({passive:!0,capture:g}),[g]),t=$a(()=>e?e():m.current?.parentElement??null,[e]),v=$a(F=>{if(!F)return 0;const G=F.offsetParent;return F.offsetTop+(G&&G instanceof HTMLElement?v(G):0)},[]),y=$a((F,G)=>F?v(F)+(F.offsetHeight-G-window.innerHeight):0,[v]),z=$a(()=>{const F=m.current;if(F){var G=t();if(G){var I=window;k?(G=document.documentElement||document.body.parentNode||
document.body,I=y(F,I.pageYOffset??G.scrollTop)):I=F.scrollHeight-G.scrollTop-G.clientHeight;I<f&&F.offsetParent!=null&&d?.()}}},[y,t,d,f,k]),A=$a(()=>{var F=t();b&&F&&(F=k?window:F,F.addEventListener("scroll",z,q),F.addEventListener("resize",z,q))},[t,b,q,z,k]),C=$a(()=>{const F=k?window:t();F&&(F.removeEventListener("scroll",z,q),F.removeEventListener("resize",z,q))},[t,q,z,k]);(0,__c.ab)(()=>{c&&z();A();return()=>{C()}},[A,C,c,z]);return(0,__c.E)("div",{ref:m,className:l,children:a})};
__c.rqf=function(a){return`${__c.Qe(__c.Oe(["lesson-templates",a]))}/`};
sqf=function(a,b,c){if(b.length!==0){var d=k=>{k-=Math.floor((a.length-1)/2);return k<0?-k+(a.length%2===0?.5:-.5):k},e=a.map((k,l)=>({column:k,index:l})).sort((k,l)=>d(k.index)-d(l.index)),f=Math.max(...b.map(k=>c(k)));b=[...b];for(var g=a.findIndex(k=>k.items.length===0);g>=0&&g<a.length;g++){const k=b.shift();if(k)a[g].Om(k,c(k));else return}b.forEach(k=>{const l=c(k),m=l/f,q=__c.jf(e,v=>v.column.Uza).column;let t=!1;for(const {column:v}of e)if(Math.abs(q.Uza-(v.Uza+m))<1.1){v.Om(k,l);t=!0;break}t||
q.Om(k,l)})}};tqf=function(a){a.columns.forEach(b=>{b.Uza=b.items.reduce((c,d)=>c+a.rBa(d),0)})};uqf=function(a){let b,c;a.items.forEach(d=>{b=Math.min(b??Number.POSITIVE_INFINITY,d.weight);c=Math.max(c??0,d.weight)});return{rvc:b,juc:c}};
yqf=function({$C:a,sg:b,title:c,description:d,uBc:e,content:f}){const g=!!(c||d||e);f=typeof f==="function"?f({$C:a,sg:b}):f;return g?vO(__c.jd,{spacing:"0",children:[typeof e!=="string"?e:wO(vqf,{children:e}),c!=null&&typeof c!=="string"?wO("div",{className:"jp8pyA",id:a,children:c}):wO(__c.wqf,{id:a,lineClamp:d?1:2,children:c}),d!=null&&typeof d!=="string"?wO("div",{className:"gCFPqQ",id:b,children:d}):wO(__c.xqf,{id:b,children:d}),f]}):f};
__c.wqf=function({className:a,weight:b="bold",lineClamp:c=2,...d}){return wO(__c.K,{className:xO("jp8pyA",a),weight:b,lineClamp:c,...d})};__c.xqf=function({size:a="small",tone:b="secondary",lineClamp:c=1,...d}){return wO(__c.K,{size:a,tone:b,lineClamp:c,className:"gCFPqQ",...d})};vqf=function({size:a="xsmall",tone:b="secondary",Q9a:c="uppercase",lineClamp:d=1,...e}){return wO(__c.K,{size:a,tone:b,Q9a:c,lineClamp:d,...e})};
Aqf=function(a){const {setConfiguration:b}=(yO(zO)??AO()).MCa,c=zqf(!0);c.current&&b(a);c.current=!1;BO(()=>{b(a)},[b,a])};__c.Cqf=function(a){const b=a?.track??!0,c=(yO(zO)??AO()).uXa;BO(()=>{b&&Bqf(()=>c.H1b=!0)},[c,b]);return c.lz};__c.Dqf=function(){const a=(yO(zO)??AO()).uXa;BO(()=>{Bqf(()=>a.Fqb=!0)},[a]);return a.isFocused};__c.Eqf=function(){const a=(yO(zO)??AO()).uXa;BO(()=>{Bqf(()=>a.Hqb=!0)},[a]);return a.isMouseDown};AO=__c.AO=function(){return{uXa:new Fqf,MCa:new Gqf}};
CO=function(a){const {borderRadius:b}=(yO(zO)??AO()).MCa.configuration;return a??b};Hqf=function({Aab:a,Pfa:b,Bw:c}){const d=a??b??c??"thumbnail";return{Aab:a??d,Pfa:b??d,Bw:c??d}};__c.EO=function({...a}){return wO(__c.oh,{...a,f4:b=>wO(__c.DO,{...b})})};Iqf=function({bounds:a,title:b,Gra:c}){return!a||a.height<103?null:a.width<200?c??b:b};Jqf=class{static F(a){vb(a,{items:qF.shallow,Om:rF})}Om(a,b){this.Uza+=b;this.items.push(a)}constructor(){this.Uza=(Jqf.F(this),0);this.items=[]}};
Kqf=class extends Jqf{static F(a){vb(a,{items:qF.shallow})}constructor(...a){super(...a);this.items=(Kqf.F(this),[])}};
__c.Lqf=class{static F(a){vb(a,{items:qF.shallow,Tk:qF.ref,wp:qF.ref,columns:qF.ref})}get columnCount(){return this.columns.length}get columnWidth(){return(this.Tk-(this.columnCount-1)*this.wp)/this.columnCount}constructor(a,b){this.items=(__c.Lqf.F(this),[]);this.Tk=1E3;this.wp=24;this.rBa=c=>{const d=c.klc?.get()??0;return c.weight*this.columnWidth+d+this.wp};this.columns=Array.from(Array(a),()=>new Jqf);b&&(this.Tk=b)}};
__c.Mqf=class{static F(a){vb(a,{X7a:rF,removeItem:rF,Bmb:rF,VCc:rF,iN:rF})}X7a(a,b){sqf(a.columns,b,a.rBa);a.items=a.items.concat(b)}removeItem(a,b){a.items=a.items.filter(c=>c.key!==b);for(const c of a.columns)c.items=c.items.filter(d=>d.key!==b)}Bmb(a,b=a.columns.length){b=Array.from(Array(b),()=>new Jqf);sqf(b,a.items,a.rBa);a.columns=b}VCc(a,b,c){a.Tk=b;a.wp=c;tqf(a)}iN(a,b){const {rvc:c=.5,juc:d=1}=uqf(a);b=__c.ch(b).map(f=>{const g=this.UUd(c,d);return{key:`placeholder-${f}`,weight:g,zRd:g}});
const e=a.columns.map(f=>{const g=new Kqf;g.Uza=f.items.reduce((k,l)=>a.rBa(l),0);return g});sqf(e,b,a.rBa);return e}constructor(){this.zTd=(__c.Mqf.F(this),(0,__c.kBc)("vertical_masonry_placeholder_seed"));this.UUd=(a,b)=>this.zTd()*(b-a)+a}};Nqf=({src:a,index:b,width:c,height:d,aspectRatio:e,border:f="none",borderRadius:g="none",shape:k,kg:l})=>__c.vI(__c.xI,{border:f,borderRadius:g,aspectRatio:e,width:c,height:d,children:__c.vI(__c.fNc,{src:a,index:b,shape:k,kg:l})});Oqf=__webpack_require__(296713);
Pqf=Oqf.Fragment;wO=__c.wO=Oqf.jsx;vO=Oqf.jsxs;var Qqf=__webpack_require__,Rqf=Qqf(208463),xO=Qqf.n_x(Rqf)();var FO,Sqf,Tqf,Uqf,Vqf,Wqf,Xqf,BO,Yqf,Zqf,zqf,$qf;FO=__webpack_require__(978109);Sqf=FO.Children;Tqf=FO.cloneElement;Uqf=FO.createContext;Vqf=FO.isValidElement;Wqf=FO.memo;Xqf=FO.useCallback;yO=__c.yO=FO.useContext;BO=FO.useEffect;Yqf=FO.useId;Zqf=FO.useMemo;zqf=FO.useRef;$qf=FO.useState;var arf=__webpack_require__(186901),brf=arf.EW,crf=arf.fm,Bqf=arf.h5,GO=arf.sH,HO=arf.XI;var drf=__webpack_require__(270531),erf=drf.iz,IO=drf.PA;var frf=__webpack_require__(594314).A;var Fqf,Gqf;
Fqf=class{static F(a){vb(a,{lz:GO.ref,isFocused:GO.ref,isMouseDown:GO.ref,H1b:GO.ref,Fqb:GO.ref,Hqb:GO.ref,yFb:brf,kYb:HO.bound,Bna:HO.bound,CYb:HO.bound})}get yFb(){const a=__c.Ad.fMb&&this.H1b;return{onMouseEnter:a?()=>this.kYb(!0):void 0,onMouseLeave:a?()=>this.kYb(!1):void 0,onFocus:this.Fqb?()=>this.Bna(!0):void 0,onBlur:this.Fqb?()=>this.Bna(!1):void 0,onMouseDown:this.Hqb?()=>this.CYb(!0):void 0,onMouseUp:this.Hqb?()=>this.CYb(!1):void 0}}kYb(a){this.lz=a}Bna(a){this.isFocused=a}CYb(a){this.isMouseDown=
a}constructor(){this.lz=(Fqf.F(this),!1);this.Hqb=this.Fqb=this.H1b=this.isMouseDown=this.isFocused=!1}};Gqf=class{static F(a){vb(a,{configuration:GO.struct,setConfiguration:HO.bound})}setConfiguration(a){this.configuration=a}constructor(){this.configuration=(Gqf.F(this),{disabled:!1,border:"none",borderRadius:"element",layout:"vertical",selected:!1,Qfa:"none",Pfa:"thumbnail",FA:"none",Bw:"thumbnail"})}};zO=__c.zO=Uqf(void 0);var grf;
__c.hrf=IO(({border:a,borderRadius:b,background:c="secondary",aspectRatio:d,padding:e,children:f,className:g,width:k,height:l,fit:m})=>{const {FA:q,Bw:t}=(yO(zO)??AO()).MCa.configuration;var v=t==="thumbnail"&&q==="bgColorTransition";var y=!!v;const z=__c.Cqf({track:y});c=y?grf[c][z?"hover":"default"]:c;b=CO(b);return wO(JO,{boundary:"thumbnail",borderRadius:b,children:wO(__c.FMc,{border:a,borderRadius:b,padding:e,background:c,width:k,height:l,aspectRatio:d,fit:m,className:xO(g,{_PWNxg:v}),children:f})})});
__c.KO=IO(({border:a="low",borderRadius:b,children:c,...d})=>{b=CO(b);a=wO(__c.xI,{...d,border:a,borderRadius:b,children:c});return wO(JO,{boundary:"thumbnail",borderRadius:b,children:a})});__c.irf=IO(({border:a="low",borderRadius:b,...c})=>{b=CO(b);a=wO(Nqf,{...c,border:a,borderRadius:b});return wO(JO,{boundary:"thumbnail",borderRadius:b,children:a})});
__c.jrf=IO(({border:a="low",borderRadius:b,...c})=>{b=CO(b);a=wO(__c.yI,{...c,border:a,borderRadius:b});return wO(JO,{boundary:"thumbnail",borderRadius:b,children:a})});__c.LO=IO(({eQ:a=__c.zI,border:b="low",borderRadius:c,...d})=>{c=CO(c);b=wO(__c.BI,{...d,border:b,borderRadius:c,src:d.src,eQ:({...e})=>a({...e,className:xO(d.className,"p0KmZA"),crossOrigin:d.crossOrigin,src:d.src,alt:d.alt||"",bTa:d.bTa})});return wO(JO,{boundary:"thumbnail",borderRadius:c,children:b})});
__c.krf=IO(a=>{const {border:b="low",borderRadius:c,className:d,Br:e,jm:f,bpc:g,apc:k,Kfb:l,eGa:m,vPc:q,k7b:t,eQ:v,Ohb:y,hSb:z,Vwa:A,autoplay:C,ref:F}=a,G=__c.Dqf(),I=CO(c);var L=__c.eb().Xf||"ADAPTIVE";L=!__c.je()&&L==="ADAPTIVE"||L==="AUTOPLAY";const O=f==null?"always":a.c4b==="always"?L?"always":"on-hover":a.c4b,P=__c.Cqf({track:O==="on-hover"}),R=erf(()=>({playState:"pause",y_d:HO(W=>{R.playState=W})})),U=R.y_d;BO(()=>crf(()=>{O!=="always"&&O!=="now"||R.playState==="play"||U("play");O==="never"&&
R.playState==="play"&&U("pause")}),[O,R.playState,U]);BO(()=>crf(()=>{O==="on-hover"&&((P||G)&&R.playState!=="play"?U("play"):P||G||R.playState!=="play"||U("pause"))}),[O,P,G,R.playState,U]);a=wO(__c.JMc,{...a,ref:F,border:b,borderRadius:I,Br:e,jm:f,playState:R.playState,autoplay:C,Fid:O==="on-hover"?150:0,k7b:t,tPc:xO("uMZn4Q",d),vPc:q,Ohb:y,hSb:z,eGa:m,eQ:v,Cyd:xO(d,"p0KmZA"),Kfb:l,bpc:g,apc:k,Vwa:A});return wO(JO,{boundary:"thumbnail",borderRadius:I,children:a})});
grf={contrastOnLight:{hover:"contrastOnLightHover",default:"contrastOnLight"},contrastOnDark:{hover:"contrastOnDarkHover",default:"contrastOnDark"},secondary:{hover:"secondaryHover",default:"secondary"},none:{hover:"secondaryHover",default:"none"}};__c.DO=function(a){const b=c=>{const [d]=$qf(AO);return wO(zO.Provider,{value:d,children:wO(a,{...c})})};b.displayName=`withCardContext(${a.displayName??a.name})`;return b}(IO(function({title:a,description:b,uBc:c,content:d,Uf:e,ariaHasPopup:f,ariaExpanded:g,ariaLabel:k,zb:l,NB:m,lba:q,href:t,target:v,draggable:y,xyb:z,nn:A,onClick:C,onDragStart:F,onDragEnd:G,onContextMenu:I,tabIndex:L,disabled:O=!1,border:P="none",borderRadius:R="element",Uqa:U,padding:W="0",background:Z="none",layout:Y="vertical",
Ua:S,BCf:ia,iI:ja,ELe:ka="1u",Aab:da,FA:la="none",Bw:ta,Qfa:pa="none",selected:Ca=!1,Pfa:xa,onPointerDown:ya,onPointerUp:sa,onPointerEnter:va,onPointerLeave:Da,onPointerMove:La,onPointerCancel:Pa}){const {Aab:bb,Bw:Wa,Pfa:pb}=Hqf({Aab:da,Bw:ta,Pfa:xa});Aqf({disabled:O,layout:Y,border:P,borderRadius:R,FA:la,Bw:Wa,selected:Ca,Qfa:pa,Pfa:pb});const gb=__c.fb(),{onMouseEnter:Ya,onMouseLeave:Sa,onMouseUp:rb,onMouseDown:Bb}=(yO(zO)??AO()).uXa.yFb;da=Yqf();ta=Yqf();const Vb=(xa=!!(a||b||c||d))?{$C:da,sg:ta}:
void 0,xb=ja!=null;var wb=lrf({zb:l,ariaLabel:k,$yb:xb,tAb:Vb});m=mrf({zb:l,ariaLabel:k,lba:q,NB:m,$yb:xb,tAb:Vb});k={horizontal:"1.5u",vertical:"1u"};l=bb==="thumbnail"&&!xa&&W==="0";la=xO("xbDyRw",{s50y4w:O,DTa6aA:gb,L_sONg:pa==="primary",HGxeEA:la==="scaleThumbnail",mc99Nw:la==="bgColorTransition"&&Wa==="card"});wb={onMouseEnter:Ya,onMouseLeave:Sa,onMouseUp:rb,onMouseDown:Bb,...wb};e=wO(nrf,{href:t,target:v,onClick:C,onPointerDown:ya,onPointerUp:sa,onPointerEnter:va,onPointerLeave:Da,onPointerMove:La,
onPointerCancel:Pa,NB:m.NB,lba:m.lba,z9a:m.z9a,ariaPressed:pa==="primary"?Ca||!1:void 0,Uf:e,ariaHasPopup:f,ariaExpanded:g,xyb:z,nn:A,disabled:O,draggable:y,onDragStart:F,onDragEnd:G,onContextMenu:I,tabIndex:L});ka={Uzc:ka==="1u"?"standard":"compact"};S=typeof S==="string"?wO(__c.LO,{src:S}):S;ia=bb==="thumbnail"?vO(__c.Tf,{...(l?wb:{}),...ka,className:xO("tEle5Q",l&&la,{AoMRfg:ia}),children:[l&&e,S,ja]}):Y==="horizontal"?wO("div",{className:"tEle5Q",children:S}):S;if(l)return ia;f=bb==="card"?__c.Tf:
__c.KNa;return wO(JO,{boundary:"card",borderRadius:R,className:xO({WMFcsw:Y==="horizontal"}),children:vO(f,{...wb,...(bb==="card"?ka:{}),className:xO(la,{foH4Lw:Z==="neutralLow",kFRwuQ:Z==="none",FpYbmA:P==="low","_6ijdOQ Hz7lZg":R==="element","Le_oLw Hz7lZg":R==="elementSmall","SFIDng Hz7lZg":R==="elementRelaxed","xyQ_VA Hz7lZg":R==="elementSoftest",ePhmMg:W==="1u",yRPdYg:W==="2u",XrLsyw:U&&W==="1u",RkUHlA:U&&W==="2u",_5KFtkw:Y==="vertical","_4eVwow WMFcsw":Y==="horizontal",gwmWnw:Ca}),children:[e,
S!=null&&vO(Pqf,{children:[ia,wO(__c.Ie,{size:k[Y],direction:Y})]}),xa&&wO(yqf,{title:a,description:b,uBc:c,$C:da,sg:ta,content:d}),bb==="card"&&ja]})})}));IO(function({children:a}){const b={lz:__c.Cqf(),isFocused:__c.Dqf(),isMouseDown:__c.Eqf()};return a(b)});
var lrf=({zb:a,ariaLabel:b,$yb:c,tAb:d})=>{if(!c)return{};c={role:"group",md:d?.sg};return a!=null?{...c,zb:a}:b!=null?{...c,ariaLabel:b}:{...c,zb:d?.$C}},mrf=({zb:a,ariaLabel:b,lba:c,NB:d,$yb:e,tAb:f})=>{e={z9a:e?void 0:f?.sg};return c!=null?{...e,lba:c}:d!=null?{...e,NB:d}:a!=null?{...e,lba:a}:b!=null?{...e,NB:b}:{...e,lba:f?.$C}},nrf=IO(function({Uf:a,ariaHasPopup:b,ariaExpanded:c,ariaPressed:d,lba:e,z9a:f,href:g,target:k,NB:l,draggable:m,disabled:q,onDragStart:t,onDragEnd:v,xyb:y,nn:z,onContextMenu:A,
tabIndex:C,onClick:F,onPointerDown:G,onPointerUp:I,onPointerEnter:L,onPointerLeave:O,onPointerMove:P,onPointerCancel:R}){const {onFocus:U,onBlur:W}=(yO(zO)??AO()).uXa.yFb,Z=Xqf(S=>S.preventDefault(),[]),Y=Xqf(()=>{},[]);return g||F?g?wO("a",{id:y,href:g,target:k,className:xO("Lmvvew",{_3zJSg:__c.qd.lC}),onClick:q?Z:F,onPointerDown:q?Z:G,onPointerUp:q?Z:I,onPointerEnter:L,onPointerLeave:O,onPointerMove:P,onPointerCancel:R,"aria-controls":a,"aria-haspopup":b,"aria-labelledby":e,"aria-describedby":f,
"aria-label":e?void 0:l,"aria-disabled":q||void 0,"aria-expanded":b&&c,draggable:m,onFocus:U,onBlur:W,onDragStart:t,onDragEnd:v,onContextMenu:A,ref:z,tabIndex:C}):wO("div",{role:"button","aria-disabled":q||void 0,"aria-controls":a,"aria-haspopup":b,"aria-expanded":c,"aria-pressed":d,"aria-label":e?void 0:l,"aria-labelledby":e,"aria-describedby":f,className:xO("Fjcg6g","Lmvvew",{_3zJSg:__c.qd.lC}),draggable:m,id:y,onClick:q?Y:F,onPointerDown:q?Y:G,onPointerUp:q?Y:I,onPointerEnter:L,onPointerLeave:O,
onPointerMove:P,onPointerCancel:R,onContextMenu:A,onFocus:U,onBlur:W,onKeyUp:S=>{q||S.key!==" "||S.currentTarget.click()},onKeyDown:S=>{q||(S.key===" "?S.preventDefault():S.key==="Enter"&&(S.preventDefault(),S.currentTarget.click()))},onDragStart:t,onDragEnd:v,ref:z,tabIndex:C??0}):null}),JO=IO(({children:a,boundary:b,borderRadius:c,className:d})=>{const {selected:e,Qfa:f,Pfa:g}=(yO(zO)??AO()).MCa.configuration,k=__c.fb();return(0,__c.OMc)(__c.ZMc)!=null||g!==b||f==="none"?a:wO("div",{className:xO("FhS5vg",
d,{gwmWnw:e,yHypLw:f==="primary",DTa6aA:k,"_6ijdOQ Hz7lZg":c==="element","Le_oLw Hz7lZg":c==="elementSmall","SFIDng Hz7lZg":c==="elementRelaxed","xyQ_VA Hz7lZg":c==="elementSoftest"}),children:a})});__c.orf=({children:a,position:b="relative"})=>a!=null?wO("div",{className:xO("lfl7zg",{TaPkRg:b==="relative"}),children:a}):null;__c.MO=IO(function({location:a,stretch:b,children:c,transition:d="fade",visibility:e="on-hover",SG:f=!1}){return wO(__c.Uf,{stretch:b,transition:d,visibility:__c.Ad.XXa?e:"always",location:a,className:f?"lfl7zg":void 0,children:c})});var qrf,rrf,prf;__c.NO=a=>wO(prf,{children:wO(qrf,{...a})});qrf=IO(function(a){var b=(yO(zO)??AO()).MCa.configuration;const c=yO(rrf),d=a.disabled??b.disabled;b=Sqf.map(a.children,e=>{if(Vqf(e))return Tqf(e,{size:a.size,disabled:d})});return wO(__c.MO,{location:a.location,visibility:c?.lCd?"always":a.visibility??"on-hover",transition:a.transition,SG:!0,children:wO(oqf,{children:b})})});
__c.OO=Wqf(function(a){const {className:b,icon:c,ariaLabel:d,onClick:e,disabled:f,size:g,variant:k="contrast"}=a;return wO(__c.Ud,{variant:k,icon:c,qf:g,size:g==="small"?"tiny":"small",ariaLabel:d,onClick:e,className:b,disabled:f})});__c.trf=IO(function(a){const b=yO(rrf),c=erf(()=>({isOpen:!1,toggle:HO(()=>{b?.r_d(!c.isOpen);c.isOpen=!c.isOpen})}));return wO(__c.srf,{...a,isOpen:c.isOpen,Q4:c.toggle})});
__c.srf=a=>{const {x5:b=__c.lg,bua:c,isOpen:d,Q4:e,ariaLabel:f=__c.J("xj5Iqw"),size:g,disabled:k,icon:l=__c.vk,className:m,variant:q="contrast",onContextMenu:t}=a,v=g==="small"?"tiny":"small";return wO(b,{width:"32u",open:d,Fa:d?e:void 0,placement:"bottom-start",trigger:y=>wO(__c.Ud,{...y,variant:q,icon:l,qf:g,size:v,disabled:k,className:m,ariaLabel:f,onClick:e,onContextMenu:t}),children:typeof c==="function"?c({Q4:e}):c})};rrf=Uqf(void 0);
prf=({children:a})=>{const [b,c]=$qf(!1),d=Zqf(()=>({lCd:b,r_d:e=>{c(e)}}),[b,c]);return wO(rrf.Provider,{value:d,children:a})};__c.urf=__c.rf({Mn:__c.DO,Tz:__c.DO});var vrf;__c.wrf=Wqf(({onClick:a,...b})=>wO(__c.DO,{onClick:a,ariaLabel:b.title,NB:b.title,Ua:wO(vrf,{...b}),layout:"vertical"}));__c.xrf=Wqf(({Da:a,onClick:b,target:c,...d})=>wO(__c.urf,{Da:a,onClick:b,target:c,ariaLabel:d.title,NB:d.title,Ua:wO(vrf,{...d}),layout:"vertical"}));
vrf=IO(({title:a,Gra:b,B5b:c,Y:d=__c.zF})=>{const e=__c.Cqf(),f=__c.Dqf(),g=__c.Eqf(),[k,l]=$qf(a);return wO(frf,{bounds:!0,onResize:({bounds:m})=>{m=Iqf({bounds:m,title:a,Gra:b});k!==m&&l(m)},children:({measureRef:m})=>wO(yd,{ref:m,border:"low",borderRadius:"baseUnit",className:xO("ufrwPQ",{CwyHxw:(e||f)&&!g,Dw_fBw:g}),height:"full",width:"full",display:"flex",alignItems:"center",children:vO(__c.jd,{spacing:"0.5u",align:"center",children:[c!=null?wO(c,{children:wO(d,{size:"medium",tone:"primary"})}):
wO(d,{size:"medium",tone:"primary"}),k&&wO(__c.K,{alignment:"center",children:k})]})})})});var PO;
__c.QO=({ou:a,G$a:b,H$a:c,I$a:d,J$a:e,m_b:f=!0})=>{switch([a,b,c,d,e].filter(g=>g).length){case 1:return wO(yd,{width:"full",height:"full",className:"PqRcZA",children:wO(yd,{height:"full",width:"full",className:xO("_5dhAxw"),children:wO(PO,{content:a,m_b:f})})});default:return wO(yd,{width:"full",height:"full",className:"PqRcZA",children:vO(__c.jd,{spacing:"2u",align:"stretch",children:[wO(yd,{height:"full",width:"full",className:"_244vrA",children:wO(PO,{content:a})}),vO(yd,{className:xO("EH8njQ","dnoK5g"),
children:[b&&wO(yd,{height:"full",width:"full",className:"_244vrA",children:wO(PO,{content:b})}),c&&wO(yd,{height:"full",className:"_244vrA",children:wO(PO,{content:c})})]}),vO(yd,{className:xO("EH8njQ","mz07ZA"),children:[d&&wO(yd,{height:"full",className:xO("_244vrA","_7Z06Og"),children:wO(PO,{content:d})}),e&&wO(yd,{height:"full",className:xO("_244vrA","_7Z06Og"),children:wO(PO,{content:e})})]})]})})}};
PO=Wqf(({content:a,m_b:b=!1})=>typeof a==="string"?wO(__c.BI,{src:a,alt:"",className:xO("xuyXsQ",{_8Gsb5Q:b}),border:"none"}):a);
}).call(globalThis, globalThis._456c437108d2d2713799e19380be528d);}

}])
//# sourceMappingURL=sourcemaps/abd2ff0ef17ce778.js.map