(globalThis["webpackChunk_canva_web"] = globalThis["webpackChunk_canva_web"] || []).push([[18463],{

/***/ 553601:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);__web_req__(945744);__web_req__(737325);__web_req__(998520);globalThis._456c437108d2d2713799e19380be528d = globalThis._456c437108d2d2713799e19380be528d || {};(function(__c) {var yd=__c.yd;var uDh=async function(a,{store:b,menu:c}){const d=rDh()();try{const {Ued:e}=d.r(await d.s(__webpack_require__.me(30774).then(()=>__c.sDh))),{O:f,store:g,Vda:k,COa:l,FUa:m}=d.r(await d.s(e({menu:c,la:a.la})));tDh(()=>{b.Vda=k;b.COa=l;b.mma=()=>f.mma(g);b.FUa=m})}finally{d.s()}},vDh=()=>{const a=(0,__c.Xa)(__c.DMa);if(!a)throw Error("HeaderContext not provided");return a},wDh=__webpack_require__(296713),xDh=wDh.Fragment,d1=wDh.jsx,e1=wDh.jsxs;var yDh=__webpack_require__(978109),zDh=yDh.Fragment,ADh=yDh.useCallback,BDh=yDh.useEffect,CDh=yDh.useRef,DDh=yDh.useState;var rDh=__webpack_require__(75402)._;var EDh=__webpack_require__,FDh=EDh(208463),GDh=EDh.n_x(FDh)();var HDh=__webpack_require__(270531).PA;var IDh=__webpack_require__(186901),tDh=IDh.h5,JDh=IDh.l_,KDh=IDh.sH;var MDh=({menu:a})=>d1("ul",{children:a.items.filter(__c.tI).map((b,c)=>d1("li",{children:d1(LDh,{menu:b.menu})},c))}),LDh=({menu:a})=>e1(xDh,{children:[a.label,d1(NDh,{menu:a})]}),NDh=({menu:a})=>e1("ul",{children:[a.items.map((b,c)=>d1("li",{children:d1(ODh,{item:b})},c)),a.F8&&d1("li",{children:d1(PDh,{action:a.F8})})]}),ODh=({item:a})=>a.type==="SUB_MENU"?d1(QDh,{menu:a.menu}):d1(RDh,{action:a.action,uI:2}),QDh=({menu:a})=>e1(xDh,{children:[d1("h2",{children:a.label}),e1("ul",{children:[a.items.filter(__c.tI).map((b,
c)=>d1("li",{children:d1(SDh,{section:b.menu})},c)),a.B8&&d1("li",{children:d1(TDh,{action:a.B8})})]})]}),SDh=({section:a})=>e1(xDh,{children:[d1("h3",{children:a.N2a??a.label}),e1("ul",{children:[a.items.filter(__c.RYe).map((b,c)=>d1("li",{children:d1(RDh,{action:b.action})},c)),a.B8&&d1("li",{children:d1(TDh,{action:a.B8})})]})]}),RDh=({action:a,uI:b})=>d1("a",{href:a.url,children:b===2?d1("h2",{children:a.label}):a.label}),TDh=({action:a})=>d1("a",{href:a.action.url,children:d1("h2",{children:a.Ada??
a.action.label})}),PDh=({action:a})=>a.zib&&d1("a",{href:a.url,children:d1("h3",{children:a.zib.label})});var YDh=HDh(({O:a,store:b,menu:c,alert:d,NH:e=zDh,bzb:f,sGd:g,t1d:k,m3b:l,Bda:m,variant:q="standard",sticky:t=!0,UPc:v=!1,A0d:y=!1,Qxa:z="signup",GS:A,zIndex:C,V3a:F=!0})=>{const G=b.mma,I=z==="login"?g:k,L=d1(__c.EMa.Provider,{value:"secondary",children:z==="login"?k:g});BDh(()=>{uDh(a,{store:b,menu:c.menu})},[a,b,c.menu]);return d1(__c.qf.Provider,{value:!0,children:d1(__c.DMa.Provider,{value:{messages:c.messages},children:d1(UDh,{variant:q,sticky:t,children:({e_d:O})=>e1(xDh,{children:[d1(VDh,
{alert:d,sticky:t,xQb:()=>O(!0),GS:A,zIndex:C,children:d1(WDh,{UPc:v,mma:G??void 0,KJd:d1(MDh,{menu:c.menu}),gp:d1(e,{children:d1(__c.fZe,{variant:c.zK})}),Vda:b.Vda??void 0,extensions:d1(XDh,{bzb:f,Qxa:I,K2a:L,m3b:l}),V3a:F})}),b.COa&&d1(b.COa,{Bda:m,...(y?{Qxa:I,K2a:L}:{})}),b.FUa]})})})})}),UDh=({children:a,variant:b,sticky:c})=>{const [d,e]=DDh(!0),[f,g]=DDh(!1);BDh(()=>{const l=window.scrollY<=0;e(l);g(!l)},[]);const k=ADh(()=>{const l=window.scrollY<=0;e(l);l&&g(!1)},[]);BDh(()=>{window.addEventListener("scroll",
k);return()=>window.removeEventListener("scroll",k)});return d1(__c.wk.Provider,{value:c&&!d&&f?"standard":b,children:a({e_d:g})})},VDh=({children:a,alert:b,sticky:c,xQb:d,GS:e,zIndex:f=1})=>{const {y4d:g}=__c.FD(),k=(0,__c.Xa)(__c.wk),l=CDh(null),[m,q]=DDh(),t=ADh(v=>{e?.(v);q(v)},[e]);return e1(yd,{ref:l,className:GDh("SzJA6w",{_4CiF0g:c,Ln0sCQ:k==="standard",E7KJ0g:k==="overlay"||k==="overlay-light",_0V2BfA:m===!1}),PBb:{"--foNLgg":f},tagName:"header",display:"flex",flexDirection:"column",justifyContent:"center",
alignItems:"stretch",width:"full",children:[g&&d1(yd,{className:GDh("Gm2LsA","fA_rnA")}),b&&d1(yd,{className:GDh("fA_rnA","LZf9eA"),width:"full",children:b}),c?d1(ZDh,{GS:t,xQb:d,children:a}):a]})},WDh=({UPc:a,mma:b,KJd:c,gp:d,Vda:e,extensions:f,V3a:g})=>{var {messages:k}=vDh(),l=(0,__c.Xa)(__c.wk);const m=k.p_b;k=k.q_b;l=d1(__c.Od,{light:l==="overlay"?"dark":"light",pn:l==="overlay"?"dark":"light",dark:"dark",nx:"dark",children:q=>d1(yd,{className:GDh(q.className,"fA_rnA"),display:"flex",justifyContent:"center",
width:"full",children:e1(yd,{className:"eRuTAw",display:"flex",alignItems:"center",ee:{default:"3u",Mc:"4u",Ug:"6u"},width:"full",children:[d1(yd,{className:"Fdg5UQ",display:"flex",justifyContent:"start",alignItems:"center",children:e1(yd,{className:GDh("Hjt0Ug","Fdg5UQ"),display:"flex",alignItems:"center",children:[g&&d1(__c.Sj,{GL:"medium",children:e1(yd,{tagName:"nav",children:[d1($Dh,{mma:b}),d1(yd,{display:"none",children:c})]})}),d]})}),d1(__c.Ie,{direction:"horizontal",size:"1u"}),d1(yd,{className:"FSXSWQ",
display:"flex",justifyContent:"center",alignItems:"center",children:g&&d1(__c.Sj,{cA:"medium",children:e??d1(aEh,{})})}),d1(__c.Ie,{direction:"horizontal",size:"1u"}),d1(yd,{className:"Fdg5UQ",display:"flex",justifyContent:"end",alignItems:"center",children:f})]})})});return a?d1(__c.gZe,{QJc:k,PJc:m,children:l}):l},$Dh=({mma:a})=>{const {messages:b}=vDh();return d1(__c.Yc,{start:"1u",children:d1(__c.Ud,{icon:c=>d1(bEh,{size:"medium",...c}),qf:"medium",size:"small",variant:"tertiary",loading:!a,disabled:!a,
onClick:a,ariaLabel:b.Bld,ariaHasPopup:"menu"})})},bEh=__c.QL(async()=>{const a=rDh()();try{return a.r(await a.s(__webpack_require__.me(156418).then(()=>__c.cEh))).dZc}finally{a.s()}},__c.dZe),aEh=()=>d1(yd,{className:"qTFgYA",children:d1(__c.md,{shape:"rectangle"})}),XDh=({bzb:a,Qxa:b,K2a:c,m3b:d})=>e1(yd,{className:"uy0XCA",display:"flex",alignItems:"center",children:[a,d??e1(xDh,{children:[d1(__c.Sj,{cA:"medium",children:c}),b]})]}),ZDh=__c.QL(async()=>{const a=rDh()();try{return a.r(await a.s(__webpack_require__.me(21775).then(()=>
__c.dEh))).fSc}finally{a.s()}},({children:a})=>a);var eEh=class{constructor({la:a}){this.la=a}};var fEh=class{constructor(){this.FUa=this.mma=this.COa=this.Vda=null;JDh(this,{FUa:KDh.ref,Vda:KDh.ref})}};var gEh=({la:a})=>{const b=new fEh,c=new eEh({la:a});return d=>d1(YDh,{O:c,store:b,...d})};var iEh=({menu:a,X:b,...c})=>{const [d]=DDh(()=>hEh({X:b}));return d1(d,{menu:a,...c})},hEh=({X:a})=>{const b=gEh({la:a&&__c.bZe(a)});return c=>d1(__c.cZe,{children:d1(b,{...c})})};__c.Uma={Cfd:({Yja:a,Aw:b,NH:c,X:d,GS:e})=>{const f=a.U8,g=b??new __c.dHa;__c.ZLc(g,{o5:!1,w_:!1,bcb:!0});const k=__c.Rb("458eacd2",!1),l=__c.Rb("4f6e585",!1);return{KH:HDh(({alert:m,GS:q,zIndex:t})=>{const v=ADh(L=>{e?.(L);q?.(L)},[q]);if(!f)return null;const y=g.fha,z=g.kha,A=g.D5,C=g.I_,F=g.variant,G=g.fjc,I=g.N_?.get();return d1(iEh,{alert:m,NH:c,menu:f,bzb:I&&d1(I,{}),sGd:y&&d1(y,{}),t1d:z&&d1(z,{}),m3b:A&&d1(A,{display:"avatarOnly"}),Bda:C&&d1(C,{}),variant:F,sticky:G,A0d:k,Qxa:l?"login":void 0,
X:d,GS:v,zIndex:t})}),Aw:g}}};
}).call(globalThis, globalThis._456c437108d2d2713799e19380be528d);}

}])
//# sourceMappingURL=sourcemaps/b2400919065583f4.js.map