(globalThis["webpackChunk_canva_web"] = globalThis["webpackChunk_canva_web"] || []).push([[23812],{

/***/ 936175:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);__web_req__(658999);__web_req__(827954);__web_req__(93415);globalThis._456c437108d2d2713799e19380be528d = globalThis._456c437108d2d2713799e19380be528d || {};(function(__c) {var yd=__c.yd;var nM;var J=__c.J;var $2e,a3e,n3e,o3e,pM;
$2e=function(a){switch(a){case "af-ZA":return J("GP3tGg");case "am-ET":return J("XVcnHQ");case "ar":return J("9fpz9Q");case "ar-AE":return J("bUQscQ");case "ar-EG":return J("Su/pSw");case "ar-SA":return J("pooITA");case "as-IN":return J("M5ei6g");case "az-AZ":return J("3Spbxg");case "bg-BG":return J("fTUpwg");case "bn-BD":return J("MZctSg");case "ca-ES":return J("Qw2UXA");case "ceb-PH":return J("SjodfQ");case "cs-CZ":return J("4aYRyA");case "cy-GB":return J("YxnMsw");case "da-DK":return J("olqOfw");
case "de-DE":return J("0T9plw");case "el-GR":return J("mE0o0w");case "en":return J("M+GdZQ");case "en-AU":return J("KVhL6Q");case "en-GB":return J("hUQ5nA");case "en-Genz":return J("oxr5NA");case "en-IN":return J("OTF4KA");case "en-PH":return J("EYENAw");case "en-psaccent":return J("Q2Ql0Q");case "es-419":return J("MYqFig");case "es-AR":return J("ULJmgA");case "es-CO":return J("I6pCeQ");case "es-ES":return J("d5FbeA");case "es-MX":return J("yreaKg");case "es-US":return J("PPrdsw");case "et-EE":return J("doIGZA");
case "eu-ES":return J("R6KWcQ");case "fa-IR":return J("jA/Zig");case "ff-SN":return J("rMpJFQ");case "fi-FI":return J("Zfzw/A");case "fr-BE":return J("fkz4bg");case "fr-CA":return J("TutTyg");case "fr-FR":return J("IoqwYQ");case "gl-ES":return J("023CgQ");case "gu-IN":return J("9JiLXg");case "ha-NG":return J("dZozAQ");case "he-IL":return J("kCr0uA");case "hi-IN":return J("UE3YQA");case "hr-HR":return J("XWHEtw");case "hu-HU":return J("Y5W5/g");case "hy-AM":return J("RjPsLQ");case "id-ID":return J("qRj64w");
case "ig-NG":return J("yO3pfQ");case "it-IT":return J("IXf4zg");case "ja-Heisei":return J("OgZL/Q");case "ja-Hira":return J("k16iMQ");case "ja-JP":return J("LmRmmw");case "jv-ID":return J("ASQOJA");case "ka-GE":return J("V+saGw");case "kk-KZ":return J("jqW6hA");case "km-KH":return J("I5K6WA");case "kn-IN":return J("CmAKmQ");case "ko-KR":return J("0u9lYA");case "ku-TR":return J("Cs6KxA");case "ky-KG":return J("n6x3xA");case "lt-LT":return J("QoSgoA");case "lv-LV":return J("++vKFg");case "ma-IN":return J("P0NX7w");
case "mg-MG":return J("vfde2A");case "mk-MK":return J("qQ1YYw");case "ml-IN":return J("UEsDxw");case "mn-MN":return J("qcNv8A");case "mr-IN":return J("LhuLjw");case "ms-MY":return J("Lk0c2Q");case "my-MM":return J("Ruzj8w");case "nb-NO":return J("U+f1MA");case "ne-NP":return J("pRfFcw");case "nl-BE":return J("30GaYA");case "nl-NL":return J("89KeWQ");case "nr-ZA":return J("TDWxzQ");case "ny-MW":return J("zb7ylQ");case "om-ET":return J("TMsXrA");case "pa-IN":return J("2onibg");case "pa-PK":return J("Y/LT1g");
case "pl-PL":return J("Z82yrA");case "pt-BR":return J("ozO2eQ");case "pt-PT":return J("hqEbuA");case "ro-RO":return J("nZ62Dg");case "ru-RU":return J("4YthYA");case "sd-IN":return J("fPF25Q");case "si-LK":return J("iY/c9g");case "sk-SK":return J("DPOHVQ");case "sl-SI":return J("J6xMxg");case "sn-ZW":return J("6Tz+6A");case "so-SO":return J("QAcNqw");case "sq-AL":return J("sxQCJQ");case "sr-RS":return J("mLCzcA");case "ss-ZA":return J("bQhgmw");case "st-ZA":return J("fgJuoQ");case "su-ID":return J("92gBRw");
case "sv-SE":return J("9hjzTQ");case "sw-KE":return J("6ww/0w");case "ta-IN":return J("rslDRQ");case "te-IN":return J("ta+dMw");case "th-TH":return J("FTxeDA");case "tl-PH":return J("FzlpeQ");case "tr-TR":return J("nzy6kA");case "tw-GH":return J("GbpV+A");case "uk-UA":return J("WrsOlg");case "ur-PK":return J("2xYYow");case "uz-UZ":return J("NsinDQ");case "vi-VN":return J("s8RRyg");case "wo-SN":return J("sZh9aQ");case "xh-ZA":return J("Ij2dLA");case "yo-NG":return J("0RzYiQ");case "zh-CN":return J("sqAsDg");
case "zh-HK":return J("qHT5bA");case "zh-TW":return J("upLoxA");case "zu-ZA":return J("0owqbw");default:throw Error(`Unknown language code: ${a}`);}};a3e=function({Xs:a,Xzc:b,crc:c}){if(a?.tags.length)return b?"MINIFIED_SIDEBAR":c?"IN_PAGE":"MINIFIED_SIDEBAR"};
__c.m3e=function({Link:a,bn:b,Yl:c,xK:d,dF:e,xa:f,Ab:g,Uh:k,$U:l}){const m=b3e(()=>{const F=__c.fua({default:__c.c3e,Mc:0});return __c.d3e+F}),q=new __c.e3e(k,e,d,m),{hub:t}=__c.Iqc({Link:a,xa:f,Ab:g}),{e6b:v}=__c.Gqc({dF:e,QAa:t,Kfa:l}),y=({children:F})=>F,z=__c.f3e({Link:a}),A=__c.g3e({Link:a}),C=__c.h3e({Link:a});return{qub:i3e(F=>{var G=__c.qe({default:!1,Mc:!0}),I=F.mha??y;const L=F.nha??y,O=b&&F.breadcrumbs?.length?nM(b,{model:F.breadcrumbs}):void 0;j3e(()=>{const ka=q.yjb();return()=>{ka()}});
const P=a3e({Xs:F.Xs,Xzc:!!F.$V,crc:G})==="IN_PAGE"?nM(t,{Xs:F.Xs,Joa:!0}):void 0,R=F.V_?nM(I,{children:nM(c,{Qo:!0,fq:F.V_})}):void 0,U=nM(L,{children:nM(__c.jd,{spacing:{default:"2u",pb:"4u"},children:nM(c,{Qo:!0,fq:F.Xi})})}),W=k3e(null),Z=F.XU;j3e(()=>{if(Z)return q.Z9(Z,()=>W.current?.scrollIntoView({behavior:"smooth"})),()=>{q.r2b()}},[Z]);const Y=!!F.XU?.filters.length,S=a3e({Xs:F.Xs,Xzc:!!F.$V,crc:G})==="MINIFIED_SIDEBAR",ia=nM(l3e,{children:()=>nM("div",{className:"_21ljAg",children:nM("div",
{className:"DECAMg",children:nM(v,{Xs:S?F.Xs:void 0,Zwd:Y,Hza:F.Hza})})})});G=F.search.R$a;let ja;if(G)switch(G.type){case "SPELLING":I=__c.h(F.search.query,"Search query is expected for spelling correction.");ja=nM(z,{Bdc:I,yNa:G.yNa,jNc:G.redirect});break;case "LANGUAGE_CORRECTION":I=__c.h(F.search.qW,"Search language override is expected for language correction.");ja=nM(A,{bcd:__c.oM(I),Ekb:__c.oM(G.S_a),Gzc:G.redirect});break;case "LANGUAGE_SUGGESTION":ja=nM(C,{QKc:__c.oM(G.TKc),Ekb:__c.oM(G.S_a),
RKc:G.redirect});break;default:throw new __c.n(G);}return nM(l3e,{children:()=>nM(__c.ql,{breadcrumbs:O,vfa:P,lZa:Y||S||F.Hza?ia:void 0,zvb:R,ZUb:ja,tw:U,Lta:F.Lta,rwb:F.rwb})})})}};n3e=__webpack_require__(296713);o3e=n3e.Fragment;nM=__c.nM=n3e.jsx;pM=n3e.jsxs;var p3e,i3e,q3e,j3e,k3e;p3e=__webpack_require__(978109);i3e=p3e.memo;q3e=p3e.useCallback;j3e=p3e.useEffect;__c.r3e=p3e.useMemo;k3e=p3e.useRef;var s3e=__webpack_require__(186901),b3e=s3e.EW,t3e=s3e.mJ,u3e=s3e.XI;var l3e=__webpack_require__(270531).nu;var v3e=__webpack_require__,w3e=v3e(208463),x3e=v3e.n_x(w3e)();var y3e,z3e;y3e=(a,b)=>{const c=new __c.LE;__c.KE(c,"a",(d,e)=>b(a,e));return c};z3e=({UVb:a,...b})=>{let c;switch(b.mode){case "spelling":c=b.jNc;b=__c.H("8v3crQ",[b.Bdc,b.yNa]);break;case "language-correction":c=b.Gzc;b=__c.H("y2LGXw",[b.Ekb]);break;case "language-suggestion":c=b.RKc;b=__c.H("iDDKFQ",[b.QKc]);break;default:throw Error("Unhandled query correction mode.");}a=y3e(c,a);return nM(__c.K,{size:"large",children:a.render(b)})};
__c.f3e=({Link:a})=>b=>nM(z3e,{mode:"spelling",...b,UVb:(c,d)=>nM(a,{model:c,Mn:e=>nM(__c.ae,{...e}),children:d})});__c.g3e=({Link:a})=>b=>nM(z3e,{mode:"language-correction",...b,UVb:(c,d)=>nM(a,{model:c,Mn:e=>nM(__c.ae,{...e}),children:d})});__c.h3e=({Link:a})=>b=>nM(z3e,{mode:"language-suggestion",...b,UVb:(c,d)=>nM(a,{model:c,Mn:e=>nM(__c.ae,{...e}),children:d})});__c.oM=a=>$2e(a).replace(/\(.+?\)/g,"").trim();__c.e3e=class{static F(a){__c.vb(a,{Z9:u3e,r2b:u3e})}Z9(a,b){this.xK({FG:a,Yla:b})}r2b(){this.dF.tHc?.({FG:void 0,ypa:void 0,Yla:void 0})}yjb(){const a=t3e(()=>this.XJb.get(),u3e(b=>{__c.iqc(this.Uh,{rootMargin:`-${b}px 0px 0px`})}),{fireImmediately:!0});return()=>{a();this.Uh.dispose()}}constructor(a,b,c,d){this.Uh=a;this.dF=b;this.xK=c;this.XJb=d;__c.e3e.F(this)}};__c.d3e=parseInt("72px",10)||0;__c.c3e=parseInt("48px",10)||0;i3e(({ZTd:a,Za:b,Mf:c,x6c:d,K1d:e,body:f,keyFrame:g,gg:k,isLoading:l,t7:m,footer:q,Tod:t})=>pM(yd,{className:"ljUU9w",background:"page",children:[t&&nM(__c.Lqc,{ariaLabel:J("GuNxLA"),value:a,size:"small"}),nM(__c.hk,{keyFrame:g||a,direction:k,Uu:"fill-height",children:l?nM(A3e,{}):pM(yd,{className:"_xxPkg",children:[nM(yd,{ee:"3u",Ah:"1u",children:pM(__c.bd,{Wc:"start",spacing:"0",children:[b&&nM(__c.Zc,{children:d}),c&&nM(__c.Zc,{children:nM(__c.dd,{spacing:"0",align:"end",children:e})})]})}),nM(__c.HC,
{direction:"vertical",Z1:{type:"shadow"},children:nM(yd,{ee:"3u",className:"_kVjNQ",children:nM(__c.jd,{spacing:"2u",children:f})})}),pM(yd,{padding:"1.5u",className:"VQ4lKQ",children:[m&&nM(B3e,{t7:m}),q]})]})})]}));
i3e(({ZTd:a,onClose:b,Za:c,Mf:d,x6c:e,K1d:f,body:g,keyFrame:k,gg:l,isLoading:m,t7:q,footer:t,Tod:v})=>{const y=q3e(z=>{const A=c??c;A!=null&&(z.stopPropagation(),A())},[c]);return nM(__c.te,{Ox:y,children:pM(yd,{height:"full",className:x3e({eLmCfQ:__c.oc(),wMd1pw:__c.oc()}),children:[v&&nM(yd,{ee:"8u",Ah:"1u",children:nM(__c.Lqc,{value:a,size:"small",Rgc:!0,ariaLabel:J("GuNxLA")})}),m?nM(A3e,{}):pM(yd,{className:"PmBKsA",children:[nM(yd,{ee:"2u",paddingBottom:"1u",children:pM(__c.hk,{keyFrame:k||
a,direction:l,children:[b&&nM(yd,{display:"flex",Ah:"1u",justifyContent:"end",children:nM(C3e,{onClose:b})}),pM(__c.bd,{Wc:"start",spacing:"1u",children:[c&&nM(__c.Zc,{children:e}),d&&nM(__c.Zc,{children:nM(__c.dd,{spacing:"0",align:"end",children:f})})]})]})}),nM(__c.hk,{keyFrame:a,direction:l,Uu:"fill-height",children:nM(__c.HC,{direction:"vertical",Z1:{type:"shadow"},tR:5,children:nM(yd,{padding:"2u",children:g})})}),t&&nM(__c.hk,{keyFrame:k||a,direction:l,ica:"not-set",Dba:"not-set",children:pM(yd,
{background:"page",className:"H3SwyQ",children:[q&&nM(B3e,{t7:q}),t]})})]})]})})});var A3e=()=>nM("div",{className:"W4xKxw",children:nM(__c.md,{shape:"rectangle"})}),B3e=({t7:a})=>pM(o3e,{children:[a,nM(__c.Ie,{size:"0.5u"})]}),C3e=({onClose:a})=>nM(__c.Zd,{variant:"tertiary",ariaLabel:J("wOFx9w"),onClick:a,icon:__c.dk,qf:"medium",size:"small"});
}).call(globalThis, globalThis._456c437108d2d2713799e19380be528d);}

}])
//# sourceMappingURL=sourcemaps/c5666ad926d8f93f.js.map