(globalThis["webpackChunk_canva_web"] = globalThis["webpackChunk_canva_web"] || []).push([[75476],{

/***/ 150235:
function(_, __, __webpack_require__) {__webpack_require__.n_x = __webpack_require__.n;const __web_req__ = __webpack_require__;__web_req__(905716);__web_req__(737068);__web_req__(278042);__web_req__(827954);globalThis._456c437108d2d2713799e19380be528d = globalThis._456c437108d2d2713799e19380be528d || {};(function(__c) {var Id=__c.Id;var KE=__c.KE;var oN;var Obf,Kbf;__c.Ebf=function(a){let b=__c.Xuc(a);b||a.type!=="VIDEO"||a.Br.type==="VIMEO_SOURCE"&&a.Br.xqa&&(b=__c.ewc.get(a.Br.xqa));if(b&&b.height!==0&&b.width!==0)return b.height/b.width};__c.Lbf=function(a){const b=Fbf(()=>({render:a,JYb:Gbf(c=>b.render=c)}));(0,__c.Hbf)(()=>{b.JYb(a)},[a,b]);return Ibf(Jbf(c=>oN(Kbf,{children:b.render(c)}))).current};
__c.Nbf=function({className:a,borderRadius:b="none",...c}){return oN(__c.yd,{...c,className:Mbf(a,"P5tQlQ",{_0KfMcQ:b==="small",EAl2xw:b==="large",_3vWvTw:b==="defaultUnsetSmallUpSmall",_2nEN_g:b==="defaultSmallSmallUpLarge",zqG3PQ:b==="defaultSmallSmallUpNone"})})};Obf=__webpack_require__(296713);Kbf=Obf.Fragment;oN=__c.oN=Obf.jsx;__c.Pbf=Obf.jsxs;var Qbf,Sbf,Ibf;Qbf=__webpack_require__(978109);__c.Rbf=Qbf.Component;Sbf=Qbf.memo;__c.Hbf=Qbf.useEffect;Ibf=Qbf.useRef;var Tbf=__webpack_require__(549056)._;var Ubf=__webpack_require__(186901),Vbf=Ubf.EW,Gbf=Ubf.XI;var Wbf=__webpack_require__(621369)._;var Xbf=__webpack_require__(270531),Fbf=Xbf.iz,Jbf=Xbf.PA;var Ybf=__webpack_require__,Zbf=Ybf(208463),Mbf=Ybf.n_x(Zbf)();__c.$bf=a=>__c.H("enCF6A",[a]);__c.acf=a=>__c.H("ShIHoA",[a]);__c.bcf=(a,b)=>__c.H("YHnrjQ",[a,b]);__c.ccf=(a,b)=>__c.H("rGfmpg",[a,b]);var dcf,ecf,fcf;
new (dcf=class extends Tbf{constructor(){super(__c.gcf);ecf()}},(()=>{class a extends(fcf=__c.Rbf){static F(b){__c.vb(b,{renderer:Vbf,title:Vbf})}get renderer(){const b=new __c.LE(c=>{this.props.C?.error(c,{Ja:"HtmlRenderer: failed to render html"})});KE(b,"contributor-link",(c,d)=>oN(this.props.Link,{model:this.props.tD.link,children:d},"contributor-link"));KE(b,"brand-link",(c,d)=>oN(this.props.Link,{model:this.props.TU&&this.props.TU.link,children:d},"brand-link"));return b}get title(){var b=this.props.q2?
__c.acf:__c.$bf;const c=this.props.q2?__c.ccf:__c.bcf;b=this.renderer.render(this.props.TU?c(__c.GD(this.props.tD.name),__c.GD(this.props.TU.name)):b(__c.GD(this.props.tD.name)));return oN("span",{className:"AHxp5Q aWBg0w",children:b})}render(){const b=this.props.PBa;return b?__c.Pbf(__c.bd,{spacing:"1.5u",Wc:"center",children:[oN(__c.Zc,{width:"containedContent",children:oN(__c.uk,{Ep:b,size:"small"})}),__c.Pbf(__c.Zc,{children:[this.props.TK,this.title]})]}):this.title}constructor(...b){super(...b);
a.F(this)}}({c:[__c.gcf,ecf]}=Wbf(a,[],[__c.Lb],fcf))})(),dcf);var hcf;
hcf=function(){const a=new __c.LE;KE(a,"H1",(b,c)=>oN(__c.Yj,{size:"xlarge",nb:"legacy",tone:Id,alignment:"inherit",children:c}));KE(a,"H2",(b,c)=>oN(__c.Yj,{size:"large",nb:"legacy",tone:Id,alignment:"inherit",children:c}));KE(a,"H3",(b,c)=>oN(__c.Yj,{nb:"legacy",tone:Id,alignment:"inherit",children:c}));KE(a,"H4",(b,c)=>oN(__c.Yj,{size:"small",nb:"legacy",tone:Id,alignment:"inherit",children:c}));KE(a,"OL",(b,c)=>oN("ol",{start:b.start,children:c}));KE(a,"UL",(b,c)=>oN("ul",{children:c}));KE(a,
"LI",(b,c)=>oN("li",{children:c}));KE(a,"P",(b,c,d)=>oN(__c.K,{tagName:"p",nb:"legacy",tone:Id,alignment:"inherit",children:c},d));KE(a,"STRONG",(b,c)=>oN("strong",{children:c}));KE(a,"U",(b,c)=>oN("u",{children:c}));KE(a,"SUP",(b,c)=>oN("sup",{children:c}));KE(a,"SUB",(b,c)=>oN("sub",{children:c}));KE(a,"BR",()=>oN("br",{}));KE(a,"A",(b,c)=>oN(__c.ae,{href:b.href,rel:b.rel,children:c}));KE(a,"EM",(b,c)=>c);return a}();__c.pN=Sbf(({Q9:a,...b})=>oN(__c.K,{tagName:"div",...b,children:hcf.render(a)}));
}).call(globalThis, globalThis._456c437108d2d2713799e19380be528d);}

}])
//# sourceMappingURL=sourcemaps/d865d79052aeec95.js.map